- CHANGELOG.md
- lib/recurly/invoice.rb
- lib/recurly/resource.rb
- lib/recurly/resource/association.rb
- spec/fixtures/invoices/refund-201.xml
- spec/fixtures/invoices/refund_amount-201.xml
- spec/recurly/invoice_spec.rb
- spec/recurly/resource_spec.rb
Refactor how associations are created in order to support the ```class_name``` option for the ```original_invoice``` ```belongs_to``` association. Instead of being an array of resource class names for each type of relation, making it an array of ```Association``` objects containing a relation type, resource class name, and an options hash for other settings like ```class_name``` if the resource class of the object does not match the resource class name of the association.
Approvers: @cbarton 
Tests:
For a site with ```line_item_refunds``` enabled:
- Find a refund invoice
- Verify that the ```original_invoice``` method on the invoice returns an invoice object for the invoice refunded
- Find a invoice that is not a refund
- Verify that the ```original_invoice``` method on the invoice …
> Add support for original_invoice link on refund invoices

- CHANGELOG.md
- lib/recurly/account.rb
- spec/fixtures/accounts/show-200.xml
- spec/recurly/account_spec.rb
This field will show up when the account is elligible and has been
location verified according to the VAT rules. It will be true when
passed and false when failed.
> Adding vat_location_valid field to Account

- CHANGELOG.md
- lib/recurly/invoice.rb
- spec/fixtures/invoices/create-201-prefix.xml
- spec/fixtures/invoices/create-201.xml
- spec/fixtures/invoices/create-with-optionals-201.xml
- spec/fixtures/invoices/preview-200.xml
- spec/fixtures/invoices/refund_amount-201.xml
- spec/fixtures/invoices/show-200-nosub.xml
- spec/fixtures/invoices/show-200-refundable.xml
- spec/fixtures/invoices/show-200-taxed.xml
- spec/fixtures/invoices/show-200-with-notes.xml
- spec/fixtures/subscriptions/preview-200-change.xml
- spec/recurly/invoice_spec.rb
cc/ @judith 
tests:
- Turn on the Country Invoice Sequencing feature with VAT taxes
- Create a VAT taxed invoice 
- `Recurly::Invoice.find(<invoice_number_with_prefix>).invoice_number_with_prefix` should find the correct invoice and return its full invoice number.
> Add Invoice#invoice_number_prefix and Invoice#invoice_number_with_prefix

- lib/recurly/resource/pager.rb
- spec/recurly/resource/pager_spec.rb
- Applies to paged resource find methods for resources not using Recurly::Resource#find (add_ons)
- Fixes #174
/cc @austinheap
> Ensures Recurly::Resource::Pager#find encodes uuids

- CHANGELOG.md
- lib/recurly/adjustment.rb
- spec/fixtures/adjustments/show-200.xml
- spec/fixtures/invoices/show-200-taxed.xml
- spec/recurly/adjustment_spec.rb
The tax information has been brought down to from the Invoice level to the Adjustment level. This unlocks those fields.
cc/ @bhelx 
```ruby
adj = Recurly::Adjustment.find('<uuid>')
puts adj.tax_type
puts adj.tax_rate
puts adj.tax_region
```
> Add 'tax_type', 'tax_region', 'tax_rate' to Adjustments

- CHANGELOG.md
- lib/recurly/billing_info.rb
- lib/recurly/resource.rb
- spec/fixtures/billing_info/show-200-bank-account.xml
- spec/recurly/billing_info_spec.rb
Adds ACH support for Billing Infos
cc/ @bhelx 
tests:
```ruby
account = Recurly::Account.find('<account-code>')
name_on_account: 'John Doe',
routing_number: '125200057',
account_number: '0123456789',
address1: '123 Fake St',
state: 'CA',
country: 'US',
zip: '94107'
}
account.billing_info.save
```
- check the billing info to see that it reflects that info
> Bank accounts (ACH feature)

- CHANGELOG.md
- lib/recurly/subscription.rb
- spec/recurly/subscription_spec.rb
For back dating bank account authorization when importing subscriptions, the API user can specify a `bank_account_authorized_at` timestamp of when that authorization occurred.
cc/ @bhelx 
tests:
```ruby
sub = Recurly::Subscription.create(
plan_code: '<plan_code>',
bank_account_authorized_at: Time.parse('2015-02-15').iso8601,
account: {
account_code: '<account_code>'
}
)
sub = Recurly::Subscription.find(sub.uuid)
puts sub.bank_account_authorized_at #> 2015-02-15T08:00:00+00:00
```
> Add bank_account_authorized_at to subscriptions

- CHANGELOG.md
- lib/recurly/transaction.rb
- spec/fixtures/transactions/show-200.xml
Adding `ip_address` to transactions now that it's exposed
https://docs.recurly.com/api/transactions#create-transaction
cc: @cbarton 
Test:
`transaction = Recurly::Transaction.find('<uuid>')`
`print transaction.ip_address`
> Ip address

- CHANGELOG.md
- lib/recurly/invoice.rb
- spec/recurly/invoice_spec.rb
cc/ @bhelx 
tests:
- Create a new invoice and make sure it is paid
- Attempt a transaction first line item refund:
```ruby
inv = Recurly::Invoice.find(<invoice_number>)
ref_inv = inv.refund([{ adjustment: inv.line_items.first, quantity: 1, prorate: false}], 'transaction')
puts ref_inv.invoice_number
```
- Create another invoice and make sure it is paid
- Attempt a transaction first open amount refund:
```ruby
inv = Recurly::Invoice.find(<invoice_number>)
ref_inv = inv.refund_amount(5_00, 'transaction')
puts ref_inv.invoice_number
```
> Add support for refund_apply_order when refunding

- CHANGELOG.md
- README.md
- lib/recurly.rb
- lib/recurly/js.rb
- spec/recurly/js_spec.rb
- spec/recurly_spec.rb
Resolves issue #159 Threadsafe Recurly.api_key?  by adding a new method that will allow developers to optionally override keys on a per thread context.
I know this is a lot like the current pull request for this issue. But this takes it a step further and allows any of the static config variable to be overridden.  Also it will only have any impact if the developer calls the Recurly.config() method.  Otherwise the normal code path stays in place.
> Threadsafe Recurly.api_key?

- README.md
Adds a badge with the current rubygems version. Makes it quick to see what is currently published.
> Add rubygems badge to README

- lib/recurly/resource.rb
When we build a `Resource` from its XML source, we are using the current classes associations, not the target class'. This will use the target class' associations when building the record.
cc/ @judith
> Use the klass that is instantiated associations when a Resource

- CHANGELOG.md
- lib/recurly/invoice.rb
- lib/recurly/transaction.rb
- spec/fixtures/transactions/show-200.xml
Implements [this API call](https://docs.recurly.com/api/invoices#offline-manual-payment) in Ruby.
```ruby
invoice = Recurly::Invoice.find('9543')
invoice.enter_offline_payment(
:payment_method => 'check',
:amount_in_cents => 1000,
:description => 'Paid with check',
:collected_at => Time.utc(2012, 12, 31)
)
```
> adds ability to enter offline payment on an invoice

- CHANGELOG.md
- lib/recurly/transaction.rb
cc/ @bhelx 
tests:
- the following should create a tax exempt charge
```ruby
t = Recurly::Transaction.create(amount_in_cents: 10_00, 
tax_exempt: true,
account: { account_code: '<account_code>' })
puts t.uuid
```
> Add tax_exempt, tax_code, accounting_code to transactions

- README.md
The documentation section for configuring the client library was missing a period which led to some confusion in setup.
This change adds markdown bullets to separate the two different required credentials.
> Clarify required API Credentials

- CHANGELOG.md
- lib/recurly/coupon.rb
- spec/fixtures/coupons/show-200.xml
**Description**:
Add support for new coupon duration attributes (duration, temporal_unit, temporal_amount)
**Additional approvers**:
@bhelx
**Testing**:
- Verify that new coupons can be created with duration=forever/single_use/temporal, single_use=true, & applies_for_months=n
- Verify that when reading all of the created coupons the values for duration, temporal_unit, temporal_amount, single_use, & applies_for_months are all correct
```
test_param_sets = [
{duration: :forever},
{duration: :single_use},
{duration: :temporal, temporal_unit: :month, temporal_amount: 3},
{single_use: true},
{applies_for_months: 3}
]
test_param_sets.each do |param_set|
puts param_set
puts Recurly::Coupon.create({name: SecureRandom.uuid, coupon_code: SecureRandom.uuid, discount_in_cents: …
```
> adding support for new coupon duration attributes

- README.md
Updating all links that referenced the old docs url.
Before: https://docs.recurly.com/api
After: https://dev.recurly.com
cc: @bhelx
> Updating docs links

- CHANGELOG.md
- lib/recurly/transaction/errors.rb
- spec/fixtures/transaction_error.xml
- spec/recurly/transaction_spec.rb
**Description**:
Adding a `gateway_error_code` to transactions since it's included in a failed transaction response.
**Additional approvers**:
cc: @bhelx 
**Testing**:
Failed transactions should now have `gateway_error_code` under `transaction_error`
> Adding `gateway_error_code`

- CHANGELOG.md
- README.md
- lib/recurly/plan.rb
- spec/recurly/plan_spec.rb
Exposing a `setup_fee_accounting` code to the client library since it's now available.
Also updated spacing and fixed a typo in the Readme, and made the spec for creating a plan a bit more robust.
> Adding setup_fee_accounting_code

- CHANGELOG.md
- lib/recurly/resource.rb
- spec/recurly/resource_spec.rb
Add support for `Resource.find_each` to be chained with other iterator methods without passing a block.
``` ruby
Recurly::Account.find_each.map {|a| a.email }
```
```ruby
Recurly::Account.find_each.map {|a| a.email }
```
> allow Resource.find_each to be chained with other iterator methods without passing a block

- CHANGELOG.md
- lib/recurly/resource.rb
- spec/recurly/resource_spec.rb
If there exist an unknown association it should just skip the element
instead of throwing an exception.
As an example, if you are using API version 2.1 and you try to fetch a bulk coupon, It will throw a NameError [here](https://github.com/recurly/recurly-client-ruby/blob/master/lib/recurly/resource.rb#L406) because it cannot find the association class for the element `<unique_coupon_codes />`. 
Approvers: @cbarton 
* Fetch a bulk coupon with the `<unique_coupon_codes />` element, it should not throw an error
```ruby
coupon = Recurly::Coupon.find('mycouponcode')
```
> Skip unknown associations in the XML

- lib/recurly/coupon.rb
- lib/recurly/transaction.rb
Adding support for creating bulk coupons and adding support for generating coupon codes from a parent coupon.
Approvers: @cbarton 
* Create a bulk coupon
```ruby
code = SecureRandom.uuid
coupon = Recurly::Coupon.create(
name: "My coupon #{code}",
coupon_code: code,
discount_in_cents: 2_00,
coupon_type: Recurly::Coupon::BULK,
unique_code_template: "'#{code}-'******'-suffix'"
)
```
* Try to generate some codes on it and it should give you back a pager:
```ruby
unique_codes = coupon.generate(10)
unique_codes.each do |c|
puts c.coupon_code
end
```
* You should also be able to pull them off of the coupon:
```ruby
coupon.unique_coupon_codes.each do |c|
puts c.coupon_code
end
```
> Bulk and unique coupons

- lib/recurly/coupon.rb
- spec/fixtures/coupons/show-200.xml
- spec/recurly/coupon_spec.rb
Supporting new paths for restoring and editing coupons
Approvers: @cbarton 
* Fetch a coupon and test that you can edit these fields:
```ruby
coupon = Recurly::Coupon.find('derp')
coupon.max_redemptions = 99
coupon.max_redemptions_per_account = 3
coupon.redeem_by_date = '2025-09-09'
coupon.description = 'derp'
coupon.invoice_description = 'derp'
coupon.save
```
* Fetch an expired coupon and restore it from the dead:
```ruby
coupon = Recurly::Coupon.find('expired')
coupon.restore!
```
> Support editing and restoring coupons

- CHANGELOG.md
- spec/recurly/plan_spec.rb
Fixes a spec related to an impossible to set `setup_fee_accounting_code`. That filed does not allow spaces.
> Fixing spec

- lib/recurly/resource.rb
- spec/recurly/resource_spec.rb
We don't want to set changed attributes when reading a resource, we only want to do that when writing to one. This change will return the changes if they're actual changes, and set the object's attribute to an empty array if they're not.
This addresses https://github.com/recurly/recurly-client-ruby/issues/222
cc: @bhelx
> Don't set changed attributes when reading a resource

- CHANGELOG.md
- lib/recurly/billing_info.rb
This allows the merchant to send a custom currency on billing info creation and update for verification purposes. For instance, if your site default is USD and you are trying to verify for EUR, you may end up having two verifications. 
```ruby
account = Recurly::Account.find('1')
first_name: 'Verena',
last_name: 'Example',
number: '4111-1111-1111-1111',
verification_value:  '123',
month: 11,
year: 2019,
currency: 'EUR'
}
account.billing_info.save!
```
Approvers: @csmb
> Add currency attribute to BillingInfo

- lib/recurly/resource.rb
- lib/recurly/transaction.rb
Description: Adds an id attribute to transactions so it can be used for transaction objects built from the xml sent in a webhook
To recreate the bug: 
```ruby
webhook_notification = Recurly::Webhook.parse(request.body.read)
transaction_id = webhook_notification.transaction.id
```
Results in the following error: 
NoMethodError: undefined method `id' for #<Recurly::Transaction:0x007fde896c7888>.
Testing the changes/fix: 
* use the parse method to parse a webhook sent for a new transaction
* call transaction and id on the webhook notification to get the uuid of the transaction
```ruby
webhook_notification = Recurly::Webhook.parse(request.body.read)
transaction_id = webhook_notification.transaction.id
```
> Set id attribute for transactions from webhooks

- lib/recurly.rb
- lib/recurly/error.rb
- lib/recurly/resource.rb
- lib/recurly/subscription.rb
This pull request addresses #235. Autoload has been removed and the ```require``` statements have been reorder to support the required dependency order.
> Remove autoload and reorder require

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
Bumping for release
* Remove Gemfile.lock, add more rubies to testing matrix [PR](https://github.com/recurly/recurly-client-ruby/pull/234)
* Remove autoload and reorder requires [PR](https://github.com/recurly/recurly-client-ruby/pull/236)
* Usage Based Billing [PR](https://github.com/recurly/recurly-client-ruby/pull/237)
> Bump 2.5.2

- spec/recurly/usages_spec.rb
Found a stray `puts` call in the specs. This was my fault.
> Remove stray puts in spec

- lib/recurly/transaction.rb
- spec/fixtures/transactions/show-200.xml
- spec/recurly/transaction_spec.rb
If it's available, the transaction may contain a `fraud` object with some fraud information. This will parse that object into a Hash. I've aliased it as `fraud_info` because I find that is easier to understand and in line with the schema.
* Make sure it prints an `int` score and a `string` decision and nothing more.
```ruby
t = Recurly::Transaction.find("35cc481437fa97b566ccf04f7bad4ae0")
puts t.fraud.inspect
#=> {"score"=>99, "decision"=>"APPROVE"}
```
> Parse Fraud object if it exists

- lib/recurly/account.rb
- lib/recurly/resource.rb
- spec/recurly/account_spec.rb
Fixed Issue https://github.com/recurly/recurly-client-ruby/issues/247
But this is only a quick fix. I think we need an audit and a conversation around all the problems with `changed_attributes` and nested models.
> Fix account.address_changed? dirty check

- CHANGELOG.md
- lib/recurly/version.rb
@csmb  Planning to do the push to rubygems tomorrow.
* Add support for free trial coupons [PR](https://github.com/recurly/recurly-client-ruby/pull/245)
* Add support for `roku_billing_agreement_id` [PR](https://github.com/recurly/recurly-client-ruby/pull/246)
* Fix `Account#address_changed?` dirty check [PR](https://github.com/recurly/recurly-client-ruby/pull/248)
* Add support for `<fraud>` if it exists on `Transaction` [PR](https://github.com/recurly/recurly-client-ruby/pull/244)
* Fix updating `unit_amount_in_cents` on `Subscription` [PR](https://github.com/recurly/recurly-client-ruby/pull/241)
* Fix stray `puts` in specs [PR](https://github.com/recurly/recurly-client-ruby/pull/239)
> Bump 2.6.0

- CHANGELOG.md
- lib/recurly/account.rb
{{[43] pry(main)> acct_hash
=> {:account_code=>"98844e8b6f850a3c8c499e326035a8",
:username=>"7b8d1c00b0c",
:first_name=>"5b8527aaeec",
:last_name=>"a4891a91319",
:company_name=>"e69c52bec5b74ff72c53f",
:email=>"e687310ab5@7eb29c7869.com",
:vat_number=>nil,
:address=>
{:address1=>"c0c1c3 test street",
:address2=>"Apt 241",
:city=>"ADAMSVILLE",
:state=>"RI",
:zip=>"02801",
:country=>"United States"}}
[44] pry(main)> account = Recurly::Account.create!(acct_hash)
NoMethodError: undefined method `changed?' for #<Hash:0x007fc038706250>
from /Users/ktobo/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bundler/gems/recurly-client-ruby-99d03c7507f1/lib/recurly/account.rb:79:in `changed_attributes'}}
reported by @karentobo 
```ruby
acct_hash =
{:account_code=>"98844e8b6f850a3c8c499e326035a8", …
```
> Fix changed? method missing on hash

- CHANGELOG.md
* Fix method missing `changed?` in `Account` [PR](https://github.com/recurly/recurly-client-ruby/pull/251)
> Bump 2.6.1

- CHANGELOG.md
- lib/recurly/version.rb
Bumps to API version 2.4
- Add `updated_at` fields [PR](https://github.com/recurly/recurly-client-ruby/pull/256)
- Add support for gift cards [PR](https://github.com/recurly/recurly-client-ruby/pull/257)
> Bump 2.7.1

- lib/recurly.rb
- lib/recurly/account.rb
- lib/recurly/api.rb
- lib/recurly/helper.rb
- lib/recurly/invoice.rb
- lib/recurly/redemption.rb
- lib/recurly/resource.rb
- lib/recurly/shipping_address.rb
- lib/recurly/subscription.rb
- spec/fixtures/accounts/create-201.xml
- spec/fixtures/accounts/index-200.xml
- spec/fixtures/accounts/show-200-space.xml
- spec/fixtures/accounts/show-200-taxed.xml
- spec/fixtures/accounts/show-200.xml
- spec/fixtures/accounts/update-200.xml
- spec/fixtures/shipping_addresses/index-200.xml
- spec/fixtures/shipping_addresses/show-200.xml
- spec/fixtures/subscriptions/show-200-inactive.xml
- spec/fixtures/subscriptions/show-200-noinvoice.xml
- spec/fixtures/subscriptions/show-200-taxed.xml
- spec/fixtures/subscriptions/show-200.xml
- spec/recurly/account_spec.rb
- spec/recurly/subscription_spec.rb
```ruby
shad = Recurly::ShippingAddress.new
shad.nickname = "Work"
shad.first_name = "Verena"
shad.last_name = "Example"
shad.company = "Recurly Inc."
shad.phone = "555-555-5555"
shad.email = "verena@example.com"
shad.address1 = "123 Main St."
shad.city = "San Francisco"
shad.state = "CA"
shad.zip = "94110"
shad.country = "US"
account = Recurly::Account.new(account_code: SecureRandom.uuid)
account.shipping_addresses = [shad]
account.save!
subscription = Recurly::Subscription.new(
plan_code: 'gold',
account: {
account_code: SecureRandom.uuid,
email: 'verena@example.com',
first_name: 'Verena',
last_name: 'Example',
billing_info: {
state: 'CA',
zip: '94110',
country: 'US',
number: …
```
> Support shipping addresses

- CHANGELOG.md
- lib/recurly/gift_card.rb
- spec/fixtures/gift_cards/index-200.xml
- spec/fixtures/gift_cards/show-200.xml
- spec/recurly/gift_card_spec.rb
Gift cards can now be canceled in the Recurly admin console if they have not already been redeemed. This adds support for the `canceled_at` timestamp on the `GiftCard` resource so that merchants can track if a gift card has been canceled or not and when the cancelation occurred.
> Add support for canceled-at field on the GiftCard resource

- lib/recurly/resource.rb
The word "base" was being prepended to base error messages. Please see Issue #211. This PR removes it.
> removes base from error messages

- Gemfile
- recurly.gemspec
Let's use the gemspec rather than the gemfile. I'll add some more explicit versions for some of these after seeing how they behave in the test matrix.
> Use gemspec instead of gemfile

- .travis.yml
- recurly.gemspec
It seems like our testing dependencies can't be fixed to work with ruby 1.9.3 (which is to be expected as it was EOL in early 2015). For now, I'm just ignoring 1.9.3 and jruby in the travis matrix. [but jruby-9000 still being tested]
They should continue to work but we will no longer automatically test them. In the meantime I'm trying to hunt down the failure in the webmock gem (which still claims to support 1.9.3).
> Fix failing dependency for ruby 1.9.3

- lib/rails/recurly.rb
The `prepend_before_filter` method is being removed, this gem causes these warnings on Rails 5:
| DEPRECATION WARNING: prepend_before_filter is deprecated and will be removed in Rails 5.1. Use prepend_before_action instead.
Fix falls back if the replacement `prepend_before_action` is unavailable.
Apologies for lack of unit test; was unable to think of a way without stubbing/mocking.
Have confirmed change works on Rails 5.0.0.1.
> Correct rails deprecation warning

- CHANGELOG.md
- lib/recurly/subscription/add_ons.rb
- spec/recurly/subscription_spec.rb
Resolves #226 - Seems this PR was abandoned so I am picking up the torch
When appending an existing add on that has a quantity, the new addon's quantity was not being respected. All new addons were being assumed to have a quantity of 1.
See original PR and this test for more details.
> Fix AddOn quantity accumulator

- .travis.yml
- recurly.gemspec
After talking to webmock maintainer, was instructed to lock `addressable` at a version before it lost 1.9.3 compatibility. This adds ruby 1.9.3 and jruby back to the testing matrix.
> Add back ruby 1.9.3 and jruby

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
* Fix coupon redemption errors [PR](https://github.com/recurly/recurly-client-ruby/pull/271)
* Remove "base" from pretty printed error messages [PR](https://github.com/recurly/recurly-client-ruby/pull/267)
* Fix rails deprecation warning [PR](https://github.com/recurly/recurly-client-ruby/pull/275)
* Add `updated_at` to `MeasuredUnit` [PR](https://github.com/recurly/recurly-client-ruby/pull/263)
* Support gift card `canceled_at` timestamp [PR](https://github.com/recurly/recurly-client-ruby/pull/264)
* Fix AddOns quantity accumulator bug from #226 [PR](https://github.com/recurly/recurly-client-ruby/pull/278)
* Fix Ruby 1.9.3 and jruby testing dependencies [PR](https://github.com/recurly/recurly-client-ruby/pull/279)
* Add new dunning event webhook …
> Bump to 2.7.4

- CHANGELOG.md
- lib/recurly/coupon.rb
- lib/recurly/resource.rb
- spec/fixtures/coupons/bulk-200.xml
- spec/recurly/coupon_spec.rb
Resolves #284
Bulk coupons do not contain the `<redemptions />` element thus the `redemptions.new` line was failing. We use the `redeem` action and should only rely on that because it's always there. I had to change the `embedded!` method so we can at least call new on embedded resources. It's perhaps worth rethinking how we do that. Those methods should be protected not private.
Here is a script you can use to check that this works.
```ruby
coupon_code = 'cm2016-bx50h76kv1'
account_code = SecureRandom.uuid
Recurly::Account.create(account_code: account_code)
coupon = Recurly::Coupon.find(coupon_code)
redemption = coupon.redeem(account_code)
puts redemption.inspect
```
> Fix redemptions on bulk coupons

- README.md
The travis badge was showing the latest build which doesn't reflect that master is actually stable.
> Make the travis badge reflect master only

- .travis.yml
- lib/recurly.rb
- lib/recurly/adjustment.rb
- lib/recurly/invoice.rb
- lib/recurly/juris_detail.rb
- lib/recurly/resource.rb
- lib/recurly/tax_type.rb
- spec/fixtures/adjustments/show-200-taxed.xml
- spec/fixtures/invoices/show-200-taxed.xml
- spec/recurly/adjustment_spec.rb
- spec/recurly/invoice_spec.rb
This will need a couple follow up PRs as I discovered some things.
1. The parser tries to guess the type of a field by name. This can cause a conflict if a field with one name may have two different types. In this case there is `tax_type` which is a String on the invoice, and `tax_type` which is of the new type `TaxType`. We are going to need to fix this but I added a shortterm workaround for now. The `from_xml` method is way too hairy for me to tackle in this PR.
2. Another issue is the parser assuming anything ending with "_in_cents" should be parsed as Money. I thought it respected the `type=integer` declaration but apparently it does not. It also defaults to the site default currency, which may be wrong in some cases. I need to address this in another PR and it will probably result in …
> Implement fields for Vertex integration

- lib/recurly/version.rb
Bumps use to API version 2.5. This is a release candidate and we cannot guarantee a stable API yet.
* Implement tax fields for Vertex integration #289
* adds geo_code to billing_info, account address, and shipping address #273
> Bump 2.8.0.rc1

- lib/recurly/invoice.rb
- lib/recurly/resource/pager.rb
If there are more than 500 line items, there will be a link to create a line item pager:
```ruby
invoice = Recurly::Invoice.find '1012'
if invoice.all_line_items.any?
invoice.all_line_items.find_each do |adjustment|
puts adjustment
end
end
```
> Add all_line_items

- lib/recurly/resource.rb
Resolves #274 
Calling `attributes` in this way has the effect of calling remote resources. I'll need to find a way to only return set attributes.
> Fix stack-level-too-deep for as_json

- lib/recurly/resource.rb
- spec/fixtures/cloudflare_error.xml
- spec/recurly/api_spec.rb
- spec/recurly/resource_spec.rb
- spec/spec_helper.rb
When Cloudflare throws a 502 error, the response is html. The failure to parse the html was preventing the GatewayError from bubbling up. This makes sure the xml parsing is ignored and the gateway error bubbles up. I'm considering following up with some autoretry logic for some of these cases. 
Reported by @akannur https://github.com/recurly/recurly-js/issues/318
> Fix cloudflare 502 error

- lib/recurly/transaction.rb
`product_code` should be writable on Adjustment and writable on Transaction. This is for Vertex integration.
> Adding product_code to Transaction and Adjustment

- lib/recurly/resource.rb
- spec/recurly/resource_spec.rb
Thanks for your work on this gem! I have a small bugfix...
We currently raise an exception if a resource cannot be found:
```ruby
Recurly::Account.find('nope') # => makes an API call to accounts/nope
#=> Recurly::Resource::NotFound: Couldn't find Account with account_code = nope
```
However, if an empty string is passed into to `.find`, we fail to catch it:
```ruby
Recurly::Account.find('') # => makes an API call to accounts/
=> #<Recurly::Account#array accept_language: nil, account_code: nil, address: nil, company_name: nil, created_at: nil, email: nil, entity_use_code: nil, first_name: nil, hosted_login_token: nil, last_name: nil, state: nil, tax_exempt: nil, username: nil, vat_number: nil>
```
While this is an edge case, I believe it's easy enough to catch and raise. It's a bit …
> Guard against passing `Resource.find` empty strings

- .travis.yml
- lib/recurly/resource.rb
Jruby+nokogiri was blowing up thanks to XML comments. This adds a line to skip any nokogiri xml comment node.
> Fix jruby+nokogiri failure on comments

- CHANGELOG.md
- Finishes API v2.5 updates [PR](https://github.com/recurly/recurly-client-ruby/pull/301)
- Adding product_code to Transactions and Adjustments [PR](https://github.com/recurly/recurly-client-ruby/pull/298)
- Adding all_line_items [PR](https://github.com/recurly/recurly-client-ruby/pull/293)
- Implement fields for Vertex integration [PR](https://github.com/recurly/recurly-client-ruby/pull/289)
- Adds geo_code to billing_info, account address, and shipping address [PR](https://github.com/recurly/recurly-client-ruby/pull/273)
- Guard against passing `Resource.find` empty strings #307
- Add yard docs link #305 
If you were are using `as_json` on a Resource (previously unsupported) we are now returning the attributes as json rather than the resource as json. This means your returned Hash will …
> Bump 2.8.0

- CHANGELOG.md
- recurly.gemspec
Recurly states this on their README:
Recurly will automatically use Nokogiri (for a nice speed boost)
if it's available and loaded in your app's environment.
This means nokogiri shouldn't be an actual dependency of Recurly, but
rather a development dependency, so developers can include it only if
they want to.
> Move nokogiri to a development dependency

- .travis.yml
- recurly.gemspec
- spec/recurly/subscription_spec.rb
- spec/spec_helper.rb
We needed to upgrade webmock to get specs to run in 2.4.0 and above. I also added it to the travis matrix. Roughly followed webmock upgrade notes: https://github.com/bblimke/webmock/blob/master/CHANGELOG.md#200
> Upgrade webmock so specs can run in 2.4.x

- .travis.yml
- README.md
- lib/recurly/xml.rb
- recurly.gemspec
Resolves #316 
The purpose of this PR is to officially deprecate ruby versions 1.9 and 2.0 and no longer allow
an insecure version of nokogiri to be used. Looks like we will also need to deprecate jruby-1.7 as it reports as ruby version 1.9.
- Bumping nokogiri to 1.7.1
- Deprecating ruby 1.9 and 2.0 and only allowing rexml use on those versions
- Conditionally install nokogiri development dependency (for ruby >= 2.1)
- Allow failures in Travis for appropriate versions with nokogiri
- Update README with supported version information
> Ban nokogiri on dead rubies

- lib/recurly/address.rb
- lib/recurly/resource.rb
Resolves #309 
It appears there are two problems biting us here:
1. The endpoint does not accept partial updates of addresses. You have to send the whole address each time. 
2. `address.changed_attributes.clear` seems like it was mutating the reference to the attributes. That should probably be changed to be a copy of the attributes and not a reference.
You should see that when updating the account, every field is serialized for the Address.
```ruby
require 'logger'
Recurly.logger = Logger.new STDOUT
account = Recurly::Account.create(address: { city: "Brussels", country: "BE", zip: "1000" }, account_code: SecureRandom.uuid)
account.address.address1 = "1234 Rue du Lombard"
account.save!
```
> Fix partial address update bug

- CHANGELOG.md
- lib/recurly/version.rb
- Remove Nokogiri as a dependency of the recurly gem. If you'd like to continue using it (for that nice speed boost), make sure to add `gem "nokogiri"` to your Gemfile. [PR](https://github.com/recurly/recurly-client-ruby/pull/302)
- Add sort and filter params to Pager rubydocs [PR](https://github.com/recurly/recurly-client-ruby/pull/318)
- Ban nokogiri on dead rubies [PR](https://github.com/recurly/recurly-client-ruby/pull/317)
- Fix Address serialization bug (serialize every attribute on update) [PR](https://github.com/recurly/recurly-client-ruby/pull/315)
- Upgrade webmock so specs can run on ruby 2.4 [PR](https://github.com/recurly/recurly-client-ruby/pull/314)
Ruby 1.9 and 2.0 are now deprecated. You may no longer use nokogiri on these rubies. Please see [PR …
> Bump 2.9.0

- CHANGELOG.md
- lib/recurly/account.rb
- lib/recurly/invoice.rb
- lib/recurly/resource.rb
- lib/recurly/transaction.rb
The `resource_class` option in the association creation helpers should be `class_name`. This was obscuring the fact that Account#shipping_addresses should not use this option so I removed it.
Also found that Resource#to_xml does not have a `delta` option.
> resource_class option should be class_name and other mislabeled options

- recurly.gemspec
This upgrades our development version of rake which gets rid of this warning:
```
$ bundle exec rake spec
/Users/ben/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-11.1.2/lib/rake/ext/fixnum.rb:4: warning: constant ::Fixnum is deprecated
/Users/ben/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/rake-11.1.2/lib/rake/ext/fixnum.rb:4: warning: constant ::Fixnum is deprecated
```
Does not affect the code or the tests at all. Just prevents the deprecation warning.
> Upgrade rake removing Fixnum warnings

- lib/recurly.rb
- lib/recurly/account.rb
- lib/recurly/purchase.rb
- lib/recurly/resource.rb
- spec/fixtures/purchases/invoice-201.xml
- spec/fixtures/purchases/invoice-422.xml
- spec/fixtures/purchases/invoice-declined-422.xml
- spec/fixtures/purchases/preview-201.xml
- spec/recurly/purchase_spec.rb
This PR adds support for the new purchases endpoint. You can give a `Purchase` a couple things:
1. An account (existing or new)
* For an existing account, you just need an account_code: `{account: {account_code: 'myexistingaccount'}}`
* For a new account, you can pass in data for billing info, account acquisition, etc. It follows the same rules as the `Subscription` endpoint.
2. An array of adjustments
3. Invoicing data: `currency`, `collection_method`, `po_number`, `terms`
```ruby
purchase = Recurly::Purchase.new({
collection_method: :automatic,
account: {
account_code: SecureRandom.uuid,
billing_info: {
first_name: 'Benjamin',
last_name: 'Du Monde',
state: 'CA',
zip: '94110',
country: 'US', …
```
> Purchases endpoint

- lib/recurly/resource/pager.rb
- spec/fixtures/accounts/index-200.xml
- spec/fixtures/gift_cards/index-200.xml
- spec/fixtures/shipping_addresses/index-200.xml
- spec/fixtures/shipping_addresses/show-200.xml
- spec/recurly/resource/pager_spec.rb
We are removing the X-Records header in api version 2.6 on paginating GET requests
and they only come back on HEAD requests. Now calling `Resource#count` or `Pager#count`
will always explicitly call the server with a HEAD request. This should maybe be considered a breaking change:
To get a count, you'll need to explicitly call count which will call the server on each call.
```ruby
params = {
begin_time: Date.today.prev_month,
order: :asc,
sort: :created_at
}
count = Recurly::Transaction.where(params).count
puts count
```
> Remove X-Records header parsing

- CHANGELOG.md
- README.md
- lib/recurly.rb
- lib/recurly/api.rb
- lib/recurly/plan.rb
- lib/recurly/purchase.rb
- lib/recurly/resource.rb
- lib/recurly/resource/pager.rb
- lib/recurly/subscription.rb
- lib/recurly/version.rb
- spec/fixtures/accounts/index-200.xml
- spec/fixtures/gift_cards/index-200.xml
- spec/fixtures/plans/show-200.xml
- spec/fixtures/purchases/invoice-201.xml
- spec/fixtures/purchases/invoice-422.xml
- spec/fixtures/purchases/invoice-declined-422.xml
- spec/fixtures/purchases/preview-201.xml
- spec/fixtures/shipping_addresses/index-200.xml
- spec/fixtures/shipping_addresses/show-200.xml
- spec/fixtures/subscriptions/show-200.xml
- spec/recurly/purchase_spec.rb
- spec/recurly/resource/pager_spec.rb
- resource_class option should be class_name and other mislabeled options [PR](https://github.com/recurly/recurly-client-ruby/pull/321)
- Upgrade rake to fix warnings [PR](https://github.com/recurly/recurly-client-ruby/pull/323)
- Purchases endpoint [PR](https://github.com/recurly/recurly-client-ruby/pull/322)
- Removal of X-Records header [PR](https://github.com/recurly/recurly-client-ruby/pull/324)
> Bump v 2.10.0

- lib/recurly/plan.rb
This field was coming back without the `type="boolean"` attribute in the xml. In order to not interrupt our 2.6 release date, I overrode the read accessor to coerce the field into a boolean (if it wasn't already). Now that the API change has been deployed we can safely remove this dead code.
```ruby
plan = Recurly::Plan.all.first
attr = plan.trial_requires_billing_info
if [true, false].include?(attr)
puts "It's a still boolean as expected"
else
puts "It's not a boolean #{attr}"
end
```
> Removes Plan#trial_requires_billing_info coercion

- lib/recurly/gift_card.rb
- lib/recurly/helper.rb
This caused an issue when creating a GiftCard with an address:
```
/Users/ben/R/recurly-client-ruby/lib/recurly/resource.rb:1085:in `fetch_associated': uninitialized constant Recurly::Addres (NameError)
Did you mean?  Recurly::Address
```
We need to remove the need to singularize and pluralize because it's so problematic. I don't want to add any dependencies to this library so we will fix this instance for now.
> "address" was being singularized as "addres"

- lib/recurly/adjustment.rb
- lib/recurly/api.rb
- lib/recurly/invoice.rb
- lib/recurly/purchase.rb
- lib/recurly/subscription.rb
- lib/recurly/transaction.rb
- spec/recurly/js_spec.rb
- spec/recurly/subscription_spec.rb
There is only one feature on API v2.7, the updates to the purchases endpoint.
```ruby
plan = Recurly::Plan.first
p = Recurly::Purchase.new({
collection_method: :automatic,
account: {
#account_code: '361eecc8-6335-4c34-b1fc-a642975bc595',
account_code: SecureRandom.uuid,
billing_info: {
first_name: 'Benjamin',
last_name: 'Du Monde',
state: 'CA',
zip: '94110',
country: 'US',
number: '4111-1111-1111-1111',
month: 12,
year: 2019,
}
},
subscriptions: [
{
plan_code: plan.plan_code,
}
],
coupon_codes: [
"couponcode",
"jyadk5mbv0",
],
gift_card: {
redemption_code: "BC3749AB38371F273"
}
})
begin
invoice = Recurly::Purchase.invoice!(p)
invoice.redemptions.each do |r|
puts r.inspect
end
rescue Recurly::Resource::Invalid => e
puts …
```
> Bumps to API version 2 7

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
This release will upgrade us to API version 2.7. There are no breaking changes.
- Added `updated_account_notification` notification event [PR](https://github.com/recurly/recurly-client-ruby/pull/326)
- Removed Plan#trial_requires_billing_info coercion [PR](https://github.com/recurly/recurly-client-ruby/pull/329)
- Fixed "address" being serialized as "addres" bug [PR](https://github.com/recurly/recurly-client-ruby/pull/330)
- Bump to API v2.7 (Purchase endpoint updates) [PR](https://github.com/recurly/recurly-client-ruby/pull/332)
> Bump 2.10.1

- .travis.yml
- README.md
Add some more information about how to use `Recurly::API.net_http` to configure the http adapter. I realized this was not documented well after being asked how to configure timeouts. 
Also needed to update `.travis.yml` to fix failures in jruby-19 and ruby 1.9.
> Show timeout configurations in README

- CHANGELOG.md
- README.md
- lib/recurly/purchase.rb
- lib/recurly/subscription.rb
- lib/recurly/version.rb
- spec/recurly/subscription_spec.rb
Fixes #338
This also contains the commit to bump us to `2.10.2`.
> Fix Subscription constructor API breakage

- CHANGELOG.md
- lib/recurly/version.rb
- Added `subscriptions` link to `Invoice` and `Transaction` [PR](https://github.com/recurly/recurly-client-ruby/pull/342)
> Bump 2.11.1

- spec/recurly/purchase_spec.rb
Seeing lots of failures like:
```
1) Failure:
Recurly::Purchase::Purchase.invoice!#test_0003_should raise a Transaction::Error error when transaction fails [/home/travis/build/recurly/recurly-client-ruby/spec/recurly/purchase_spec.rb:32]:
[Recurly::Transaction::Error] exception expected, not
Class: <Recurly::Transaction::DeclinedError>
Message: <"Your transaction was declined. Please use a different card or contact your bank.">
---Backtrace---
/home/travis/build/recurly/recurly-client-ruby/lib/recurly/transaction/errors.rb:99:in `validate!'
/home/travis/build/recurly/recurly-client-ruby/lib/recurly/purchase.rb:130:in `post'
/home/travis/build/recurly/recurly-client-ruby/lib/recurly/purchase.rb:112:in `invoice!'
/home/travis/build/recurly/recurly-client-ruby/spec/recurly/purchase_spec.rb:32 …
```
> Try to fix the jruby specs

- lib/recurly/api.rb
- lib/recurly/billing_info.rb
- lib/recurly/invoice.rb
- lib/recurly/purchase.rb
- lib/recurly/transaction.rb
- spec/recurly/invoice_spec.rb
- spec/recurly/purchase_spec.rb
This PR implements the changes in API version 2.9.
1. We added the authorize endpoint for purchases. This is currently only used with Adyen. Example:
```ruby
plan = Recurly::Plan.first
p = Recurly::Purchase.new({
collection_method: :automatic,
customer_notes: 'Some notes for the customer.',
terms_and_conditions: 'Our company terms and conditions.',
vat_reverse_charge_notes: 'Vat reverse charge notes',
account: {
email: 'benjamin.dumonde@example.com', # email required
first_name: 'Benjamin',
last_name: 'Du Monde',
account_code: SecureRandom.uuid,
billing_info: {
external_hpp_type: :adyen, # billing info should use adyen external hpp
first_name: 'Benjamin',
last_name: 'Du Monde',
state: 'CA',
zip: …
```
> API Version 2.9

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
- Added purchase authorize endpoint and other API version 2.9 changes. [PR](https://github.com/recurly/recurly-client-ruby/pull/347)
This version bumps us to API version 2.9. There are a few breaking changes.
1. The 'subscription' link on an instance of `Adjustment` is now only created if adjustment is
originating from a subscription plan charge, setup fee, add on, trial or proration credit.
It is no longer created for other adjustments.
2. Instances of `Transaction` and `Invoice` no longer have a `subscription` link and you must now
use the `subscriptions` link.
> Bump 2.12.0

- lib/recurly/account.rb
- spec/fixtures/billing_info/verify-cvv-200.xml
- spec/fixtures/billing_info/verify-cvv-locked-400.xml
- spec/fixtures/billing_info/verify-cvv-transaction-err-422.xml
- spec/recurly/account_spec.rb
Implements the `POST /accounts/{account_code}/billing_info/verify_cvv` endpoint for API 2.10:
```ruby
acct = Recurly::Account.find("benjamin-du-monde")
begin
billing_info = acct.verify_cvv!("504")
rescue Recurly::API::BadRequest => e
e.message # => "This credit card has too many cvv check attempts."
rescue Recurly::Transaction::Error => e
e.transaction_error_code # => "fraud_security_code"
e.gateway_error_code # => "fraud"
rescue Recurly::Resource::Invalid => e
e.message # => "verification_value must be three digits"
end
```
> Verify CVV Endpoint

- lib/recurly/adjustment.rb
- spec/fixtures/adjustments/show-200.xml
- spec/recurly/adjustment_spec.rb
This is a small addition that had to be made to API 2.9. This will be released on Thursday so it is blocked. I will do a bump and release on Thursday night or Friday morning. It will become part of `2.12.1`.
> Adds proration_rate float to Adjustment

- lib/recurly/invoice.rb
- lib/recurly/subscription.rb
- spec/fixtures/subscriptions/preview-200-change.xml
- spec/recurly/subscription_spec.rb
This contains 2 breaking changes:
`mark_failed` no longer reloads the invoice with the response returning true or false, it returns either an `InvoiceCollection` if failable and request is successful, it returns `false` if invoice cannot be marked failed. To keep functionality, take the `charge_invoice` of the returned collection:
```ruby
invoice = Recurly::Invoice.find('1001')
failed_collection = invoice.mark_failed
if failed_collection
invoice = failed_collection.charge_invoice
end
```
Subscription previews and preview changes now return `InvoiceCollection`s rather than `Invoice`. Utilize the `charge_invoice` to keep functionality the same:
```ruby
subscription.preview
invoice = subscription.invoice
invoice = subscription.invoice_collection.charge_invoice
```
> Updates to credit memos feature

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
- Updates to credit memos feature [PR](https://github.com/recurly/recurly-client-ruby/pull/360)
`mark_failed` no longer reloads the invoice with the response returning true or false, it returns either an `InvoiceCollection` if failable and request is successful, it returns `false` if invoice cannot be marked failed. To keep functionality, take the `charge_invoice` of the returned collection:
```ruby
invoice = Recurly::Invoice.find('1001')
failed_collection = invoice.mark_failed
if failed_collection
invoice = failed_collection.charge_invoice
end
```
Subscription previews and preview changes now return `InvoiceCollection`s rather than `Invoice`. Utilize the `charge_invoice` to keep functionality the same:
```ruby
subscription.preview
invoice = subscription.invoice
invoice = …
```
> Bump 2.14.0

- lib/recurly/resource.rb
- lib/recurly/resource/pager.rb
- spec/recurly/resource/pager_spec.rb
- spec/recurly/resource_spec.rb
- spec/spec_helper.rb
This PR takes the fixes and improvements from #334 without the breaking changes. I'd like to keep working on it 334 but struggling to communicate how users with complex integrations will safely be able to upgrade. For now, I'd like to focus on documentation and best practices to rather than removing all the confusing and spurious functionality. This PR just fixes the bug and improves docs.
* Resource#find_each should accept options (not just per_page)
* Add more documentation
* Add more specs
> Fixes to pagination

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
- Invoice refunds do not return InvoiceCollection [PR](https://github.com/recurly/recurly-client-ruby/pull/363)
- Support gift card webhook [PR](https://github.com/recurly/recurly-client-ruby/pull/344)
- Fixes to Resource#find_each [PR](https://github.com/recurly/recurly-client-ruby/pull/355)
If you are upgrading from 2.13.X or 2.14.X, a design bug was fixed. `Invoice#refund` and `Invoice#refund_amount` once again return an `Invoice` and not an `InvoiceCollection`.
`Resource#find_each` previously only accepted `per_page` but now accepts an `options` Hash for pagination params. If you want to preserve functionality:
```ruby
Recurly::Invoice.find_each(50) do |invoice|
puts invoice
end
Recurly::Invoice.find_each(per_page: 50) do |invoice|
puts invoice
end
```
> Bump 2.15.0

- CHANGELOG.md
- lib/recurly/version.rb
- Fix nokogiri security warnings [PR](https://github.com/recurly/recurly-client-ruby/pull/367)
- API v2.11 changes [PR](https://github.com/recurly/recurly-client-ruby/pull/366)
> Bump 2.15.1

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
- Keep original_invoice link on Invoice #372
- Coupon#redeem! should raise Invalid on failure #371
> Bump 2.15.2

- .travis.yml
- README.md
- recurly.gemspec
We will no longer officially support ruby 2.1 since it's EOL date was last year. This PR updates the readme and allows 2.1 tests to fail in travis. I've also added a warning in the gemspec for users on older versions of ruby.
> Drop Ruby 2.1 Support

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
This brings us to API version 2.12. It has no breaking changes that need to be addressed.
- API version 2.12 [PR](https://github.com/recurly/recurly-client-ruby/pull/378)
- New Credit Invoice Webhooks [PR](https://github.com/recurly/recurly-client-ruby/pull/380)
> Bump 2.15.4

- lib/rails/recurly.rb
Follow up from conversation in #381 
This prevents the railtie from setting the logger. We want users to explicitly opt-in to logging for security reasons.
> Dont set the logger in railtie

- lib/recurly/money.rb
- spec/recurly/money_spec.rb
Previously the currencies method on Money was protected. However, the
eql? method depends upon the currencies method being public, resulting
in two instances of Money with the same attributes not to be considered
equal to one another.
This commit exposes currencies publicly to fulfill the dependencies in
the eql? method.
> Make currencies method public

- lib/recurly/purchase.rb
For API version 2.13. Allows programmer to set the gateway for a purchase. If this changes, I will follow up with another PR on the `api_version_2_13` branch.
> Allow programmer to set gateway code in purchase

- lib/recurly/invoice.rb
- spec/fixtures/invoices/show-200.xml
- spec/recurly/invoice_spec.rb
Adds the `all_transactions` link to invoices. This is only present when there are over 500 transactions. You can check for presence with `Pager#any?`
```ruby
if invoice.all_transactions.any?
end
```
> Add all_transactions link to Invoice

- CHANGELOG.md
- lib/recurly.rb
- lib/recurly/account.rb
- lib/recurly/custom_field.rb
- lib/recurly/resource.rb
- lib/recurly/subscription.rb
- spec/fixtures/accounts/show-200.xml
- spec/fixtures/subscriptions/show-200.xml
- spec/recurly/account_spec.rb
- spec/recurly/resource_spec.rb
- spec/recurly/subscription_spec.rb
Adds `Recurly::CustomField` model with associations:
- **Account** `has_many :custom_fields`
- **Subscription** `has_many :custom_fields`
*Updating Account Custom Fields*
```ruby
> account.custom_fields
=> [#<Recurly::CustomField name: "dog_breed", value: "Pompoo">, #<Recurly::CustomField name: "dog_dad", value: "Clownsworth">]
> account.custom_fields << Recurly::CustomField.new(name: "dog_mom", value: "Cinderella")
=> [#<Recurly::CustomField name: "dog_breed", value: "Pompoo">, #<Recurly::CustomField name: "dog_dad", value: "Clownsworth">, #<Recurly::CustomField name: "dog_mom", value: "Cinderella">]
> account.custom_fields[1].value = nil
=> nil
> account.custom_fields[1].value = ""
irb(main):021:0> account.save
=> true
```
*Updating Subscription Custom Fields*
```ruby
> …
```
> Custom Fields

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
- Don't set the logger in railtie [PR](https://github.com/recurly/recurly-client-ruby/pull/382)
- Make currencies method public [PR](https://github.com/recurly/recurly-client-ruby/pull/386)
- Allow programmer to set gateway code in purchases [PR](https://github.com/recurly/recurly-client-ruby/pull/387)
- Add all_transactions link to Invoice [PR](https://github.com/recurly/recurly-client-ruby/pull/384)
- Auth and Capture for Purchases [PR](https://github.com/recurly/recurly-client-ruby/pull/389)
- Custom Fields [PR](https://github.com/recurly/recurly-client-ruby/pull/391)
- Remove rails code and railtie [PR](https://github.com/recurly/recurly-client-ruby/pull/388)
- Subscription Terms [PR](https://github.com/recurly/recurly-client-ruby/pull/390)
This brings us up to API version 2.13. The …
> Bump 2.16.0

- lib/recurly/purchase.rb
Fixed missing comma in example docs, as well as minor typos.
> Adjust inline documentation for clarity, grammar, and syntax

- lib/recurly/purchase.rb
The Purchase endpoints were changed to return InvoiceCollection rather than Invoice.
> Correctly document the response type in Purchases

- .travis.yml
- lib/recurly/schema/schema_validator.rb
And fix an issue with 2.3 where a value like `2` is represented as a `Fixnum` rather than an `Integer` like in later versions.
> [V3] Test more versions of ruby

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
- Adjust inline documentation for clarity, grammar, and syntax [PR](https://github.com/recurly/recurly-client-ruby/pull/393)
- Correctly document the response type in Purchases [PR](https://github.com/recurly/recurly-client-ruby/pull/394)
- Add gateway_token and gateway_code attributes to BillingInfo class [PR](https://github.com/recurly/recurly-client-ruby/pull/395)
- Remove the old recurly binary [PR](https://github.com/recurly/recurly-client-ruby/pull/398)
> Bump 2.16.1

- lib/recurly/subscription.rb
Custom fields can now be updated through the `/notes` path. This allows you to change the custom fields without inadvertently making a subscription change. Examples:
```ruby
subscription.custom_fields << Recurly::CustomField.new(name: 'food', value: 'taco')
subscription.update_notes({})
subscription.custom_fields.first.value = nil
subscription.update_notes(terms_and_conditions: 'New T&C')
#=>
> 2.14 custom fields on notes

- CHANGELOG.md
- README.md
- lib/recurly/address.rb
- lib/recurly/api.rb
- lib/recurly/invoice.rb
- lib/recurly/subscription.rb
- lib/recurly/version.rb
- spec/fixtures/invoices/show-200-updated.xml
- spec/recurly/invoice_spec.rb
This brings us up to API version 2.14. There are no breaking changes.
- Support TransactionAuthorizedNotification webhook [PR](https://github.com/recurly/recurly-client-ruby/pull/404)
- Support updating an invoice from client [PR](https://github.com/recurly/recurly-client-ruby/pull/399)
- Support custom fields on Subscription#update_notes [PR](https://github.com/recurly/recurly-client-ruby/pull/409)
> Release 2.16.2 / API version 2.14

- lib/recurly.rb
- lib/recurly/account.rb
- lib/recurly/note.rb
- spec/fixtures/accounts/notes/show-200.xml
- spec/fixtures/accounts/show-200.xml
- spec/recurly/account_spec.rb
Fixes #327. Client could not access account notes using `account.notes`. Requires an API change (notes href tag must be included in Account xml).
> Support account notes

- lib/recurly/client.rb
- lib/recurly/client/adapter.rb
- recurly.gemspec
Should discuss some configuration and dependency management here.
Tested against this script:
```ruby
require 'recurly'
require 'benchmark'
API_KEY = 'KEY'
SITE_ID = 'subdomain-SUBDOMAIN'
@client = Recurly::Client.new(api_key: API_KEY, site_id: SITE_ID)
ids = @client.list_accounts(limit: 30).each_page.first.map(&:id)
measurement = Benchmark.measure do
ids.each do |id|
acct = @client.get_account(account_id: id)
end
end
puts measurement
```
Without persistent:
`0.520000   0.040000   0.560000 ( 11.453849)`
With persistent:
`  0.390000   0.030000   0.420000 (  4.655093)`
With persistent, the wall-clock time is over halved.
> Use Net-http-persistent for persistent connection

- lib/recurly/invoice.rb
The way `%w()` is interpreted does not allow comments. Each token in the comment was being interpreted as part of the list. It was not causing any problems so we didn't notice.
```
[9] pry(main)> Recurly::Invoice.new.methods.grep /shows/
=> [:shows,
:shows_changed?,
:shows_previously_changed?,
:shows_previously_was,
:shows=,
:shows?,
:shows_change,
:shows_was]
[10] pry(main)> Recurly::Invoice.new.methods.grep /#/
=> [:"#",
:#=,
:"#?",
:"#_change",
:"#_changed?",
:"#_was",
:"#_previously_changed?",
:"#_previously_was"]
```
> Remove comment being interpreted as atoms

- lib/recurly/invoice.rb
- spec/recurly/invoice_spec.rb
These credit invoice options were missing from the invoice refund methods. This commit is meant to add the functionality without any breaking changes. The next available minor release (2.17.0) will change the method signatures of both `refund` and `refund_line_items`.
These options can now be passed to both `refund` and `refund_line_items`.
Examples from @judith :
To refund a charge invoice:
```ruby
invoice = Recurly::Invoice.find('1001')
adjustments = invoice.line_items.map do |adjustment|
{ adjustment: adjustment, quantity: 1, prorate: false }
end
options = {
credit_customer_notes: 'Credit Notes',
external_refund: true,
payment_method: 'check',
description: 'Check no. 12345678',
refunded_at: DateTime.new(2018, 12, 1, 0, 0, 0) # can take a datetime or a string
}
refund = …
```
> Adds missing credit memo opts to invoice refunds

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
- Remove Recurly.js v2 code and some other small improvements [PR](https://github.com/recurly/recurly-client-ruby/pull/411)
- Adds missing credit memo opts to invoice refunds [PR](https://github.com/recurly/recurly-client-ruby/pull/415)
This release contains one breaking change. Older Recurly.js token signing is not longer supported. You should upgrade to version 4 of Recurly.js: https://dev.recurly.com/docs/recurlyjs
The `js` module is still around to support storing the `public_key`.
> Bump 2.17.0

- lib/recurly/client.rb
- lib/recurly/client/adapter.rb
- spec/recurly/client_spec.rb
I realized that most of what we were setting in the Adapter class could be done using Faraday's built in options.
> Move SSL and timeout config to Faraday options

- CHANGELOG.md
- lib/recurly.rb
- lib/recurly/account.rb
- lib/recurly/api.rb
- lib/recurly/note.rb
- lib/recurly/version.rb
- lib/recurly/webhook.rb
- lib/recurly/webhook/low_balance_gift_card_notification.rb
- spec/fixtures/accounts/notes/show-200.xml
- spec/fixtures/accounts/show-200.xml
- spec/fixtures/webhooks/low-balance-gift-card-notification.xml
- spec/recurly/account_spec.rb
- spec/recurly/webhook_spec.rb
This brings us up to API version 2.15. There are no breaking changes.
- Add support for Low Balance Gift Card Notification [PR](https://github.com/recurly/recurly-client-ruby/pull/414)
- Support Account Notes [PR](https://github.com/recurly/recurly-client-ruby/pull/405)
> Release version 2.17.1 / API version 2.15

- lib/recurly/account.rb
- spec/recurly/account_spec.rb
When included in transaction.details, the account xml uses `company` instead of `company_name`. This aliases the two so calling`account.company` will give you the `company_name`.
```ruby
txn = Recurly::Transaction.find('473e49b3fbce91bc3a94c34b61a1cb7d')
puts txn.details['account'].company      # prints "Your Company Name"
puts txn.details['account'].company_name # prints "Your Company Name"
```
> Alias company and company_name

- lib/recurly/resource/pager.rb
Fixes #375
In v2.3, the API changed to support updated_at sorting and filtering. Because of this, cursor is no longer an integer.
> Remove line that assumes cursor is an integer

- lib/recurly/api/errors.rb
- lib/recurly/xml.rb
- lib/recurly/xml/nokogiri.rb
- lib/recurly/xml/rexml.rb
- spec/recurly/api/errors_spec.rb
- spec/recurly/xml_spec.rb
Sometimes errors come back from Recurly as HTML, which makes REXML choke while trying to log the error, so the real error is lost to us. If we handle the error a bit more gracefully then we can log the original backtrace and error.
I did think about doing this in the `REXMLAdapter` module, but I thought that we don't always want to quietly swallow malformed XML exceptions - e.g. if the response is OK and we should have valid subscription XML but don't, then we should blow up.
Because this code is specific to REXML, I've wrapped it up so it won't run when running the test suite for nokogiri. nokogiri seems to accept HTML just fine and doesn't throw a parse error.
> Handle malformed XML errors gracefully.

- README.md
In #388, the code for the rails config generator and railtie was removed. This updates the README to reflect the removal of the generator with a note to create ones own initializer for usage in Rails / maintaining old behavior.
> Remove Rails generator mention from README

- CHANGELOG.md
- lib/recurly/api.rb
- lib/recurly/version.rb
This brings us up to API version 2.16. There are no breaking changes.
- Remove Rails Generator mention in README.md [PR](https://github.com/recurly/recurly-client-ruby/pull/426)
- Gracefully handle XML parsing errors [PR](https://github.com/recurly/recurly-client-ruby/pull/424)
- Add missing webhook properties to models [PR](https://github.com/recurly/recurly-client-ruby/pull/422)
- Do not assume cursor is an integer [PR](https://github.com/recurly/recurly-client-ruby/pull/421)
- Fix bundler warnings [PR](https://github.com/recurly/recurly-client-ruby/pull/420)
- Alias company and company_name [PR](https://github.com/recurly/recurly-client-ruby/pull/413)
> Release version 2.17.2 / API version 2.16

- lib/recurly/account.rb
- spec/recurly/account_spec.rb
The 8908a771c commit broke the functionality for looking up an account and getting `company_name`.
This commit will fix that bug while preserving the intended functionality.
> Fix bug when company is not included in xml response

- CHANGELOG.md
- lib/recurly/version.rb
- Fix bug related to aliasing company and company_name [PR](https://github.com/recurly/recurly-client-ruby/pull/428)
> Release version 2.17.3

- lib/recurly/invoice.rb
- lib/recurly/subscription.rb
- spec/fixtures/invoices/show-200-updated.xml
- spec/fixtures/invoices/show-200.xml
- spec/fixtures/subscriptions/notes-200-change.xml
- spec/fixtures/subscriptions/show-200.xml
- spec/recurly/invoice_spec.rb
- spec/recurly/subscription_spec.rb
Adds gateway code to Invoice and Subscription objects for use with the `PUT invoice` and `PUT subscription/notes` endpoints
Scripts:
```ruby
invoice = Recurly::Invoice.find('1001')
invoice.gateway_code = 'jhpqd551evcn'
invoice.save()
```
```ruby
sub = Recurly::Subscription.find '489cf44ca794cd40b1e4b64c1db63023'
sub.update_notes(gateway_code: 'jotgbnxnecn0')
```
> Add gateway_code to invoice and subscription

- lib/recurly/resource.rb
- recurly.gemspec
- spec/fixtures/subscriptions/create-422.xml
- spec/recurly/resource_spec.rb
When there is a single error returned from the API, the message attribute is blank. An example XML response from the API happens when you create a subscription on an account that has been closed:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<error>
<symbol>subscription.account</symbol>
<description>Cannot purchase on canceled account</description>
</error>
```
Because the `apply_errors` method assumes this should be an array of `errors` instead of a single error, it does not properly assign a message to the exception that is raised. So the following script would fail to provide a message:
```ruby
begin
subscription = Recurly::Subscription.create!(
:plan_code => 'gold',
:currency  => 'USD',
:account   => {
:account_code => 'some-closed-account',
}
)
rescue Recurly::Resource::Invalid => e …
```
> Ensure error message for a single returned error

- lib/recurly/billing_info.rb
Adds an additional attribute `amazon_region` to the billing info object.
```ruby
account = Recurly::Account.find('a')
:first_name         => 'John',
:last_name          => 'Jacob Jinglheimer Schmidt',
:address1           => '123 Paper Street',
:city               => 'Los Angeles',
:state              => 'CA',
:zip                => '95312',
:country            => 'US',
:phone              => '213-555-5555',
:amazon_billing_agreement_id => 'C02-2000965-4255444',
:amazon_region      => 'uk'
}
account.billing_info.save!
```
> Add Amazon Region to Billing Info

- lib/recurly/account.rb
- spec/fixtures/accounts/hierarchy/create-201.xml
- spec/fixtures/accounts/hierarchy/show-child-200.xml
- spec/fixtures/accounts/hierarchy/show-children-200.xml
- spec/fixtures/accounts/hierarchy/show-parent-200.xml
- spec/fixtures/accounts/hierarchy/update-200.xml
- spec/fixtures/accounts/hierarchy/update-no-parent-200.xml
- spec/recurly/account_spec.rb
This PR adds support for account hierarchy.
```ruby
account = Recurly::Account.create(
:account_code => 'example-123',
:parent_account_code => 'example-124'
)
```
> Add support for account hierarchy

- CHANGELOG.md
- lib/recurly/version.rb
- Fix typo in Changelog [PR](https://github.com/recurly/recurly-client-ruby/pull/440)
- Ensure error message for a single returned error [PR](https://github.com/recurly/recurly-client-ruby/pull/441)
> Bump to version 2.17.5

- CHANGELOG.md
- lib/recurly/api.rb
- lib/recurly/billing_info.rb
- lib/recurly/version.rb
This brings us up to API version 2.18. There are no breaking changes.
- Add support for Amazon Regions [PR](https://github.com/recurly/recurly-client-ruby/pull/445)
> Release version 2.17.6 / API version 2.18

- lib/recurly/xml.rb
When upgrading to a new version of this gem I received the following
message
```
You are attempting to use an insecure version of
nokogiri on an insecure version of ruby. Please see
the documentation on supported versions for more
information:
https://github.com/recurly/recurly-client-ruby#supported-versions
```
The anchor `#supported-versions` is incorrect (possibly an older version
of the README.
Here we correct the link with the proper anchor:
[`https://github.com/0xtobit/recurly-client-ruby#supported-ruby-versions`](https://github.com/0xtobit/recurly-client-ruby#supported-ruby-versions)
> Fix link to supported versions section of README

- lib/recurly/resource.rb
- spec/fixtures/plans/show-422.xml
- spec/fixtures/purchases/invoice-422.xml
- spec/recurly/plan_spec.rb
- spec/recurly/purchase_spec.rb
Fixes #400 
A `NoMethodError` was being thrown when the `invalid!` method was being called on children of a Resource that are not indeed Resources themselves. There were two examples of this found in the wild:
1) When a purchase was made with a subscription that had an invalid subscription add on, the subscription add on object is a `Pager`, not a `Resource`, and therefore had no `invalid!` method.
2) When a plan was updated with an invalid currency, the `plan.unit_amount_in_cents` is a `Recurly::Money` rather than a `Resource`, and therefore does not have an `invalid!` method.
The library previously assumed that all children of `Resource`s are also `Resource`s. This PR fixes a particular instance of this assumption.
The included specs are similar to the actual reports from #400. The code …
> Fix NoMethodError thrown by Resource.invalid!

- lib/recurly.rb
- lib/recurly/account.rb
- lib/recurly/account_acquisition.rb
- spec/fixtures/account_acquisition/show-200.xml
- spec/fixtures/accounts/show-200.xml
- spec/recurly/account_spec.rb
This PR adds support for [Account Acquisition](https://docs.recurly.com/docs/account-acquisition-data).
Create script:
```ruby
acct = Recurly::Account.find 'x'
acct.account_acquisition = {
cost_in_cents: 300,
currency: "USD",
channel: "marketing_content",
subchannel: "The coolest content we have made them sign up!",
campaign: "mailchimp67a904de95.0914d8f4b4"
}
acct.save!
```
Lookup an account acquisition:
```ruby
acct = Recurly::Account.find 'x'
acquisition = acct.account_acquisition
puts acquisition
```
Update:
```ruby
acct = Recurly::Account.find 'x'
acct.account_acquisition.cost_in_cents = 299
acct.account_acquisition.subchannel = "The 2nd coolest content we have made them sign up!"
acct.account_acquisition.save!
```
Delete:
```ruby
acct = Recurly::Account.find 'x'
if acquisition = …
```
> Add support for Account Acquisition

- CHANGELOG.md
- lib/recurly/version.rb
- Add support for Account Acquisition [PR](https://github.com/recurly/recurly-client-ruby/pull/450)
- Fix link to supported versions section of README [PR](https://github.com/recurly/recurly-client-ruby/pull/454)
- Fix NoMethodError thrown by Resource.invalid! [PR](https://github.com/recurly/recurly-client-ruby/pull/455)
> Bump to version 2.17.7

- lib/recurly.rb
- lib/recurly/schema/json_deserializer.rb
Adds a "strict" mode which makes the client more conservative about parsing / serializing. If it finds something that is off, it will throw an exception. This will be mostly useful for smoke testing.
> Add strict mode for json deserializer

- lib/recurly/client.rb
- spec/recurly/client_spec.rb
The items used in `interpolate_path` need to be encoded for the url. Example to demonstrate the problem:
```ruby
account_code = create_account(code: "benjamin.dumonde@example.com spacehere").code
account = @client.get_account(account_id: "code-#{account_code}")
puts "Got Account #{account}"
```
> Url Encode Path items

- lib/recurly/billing_info.rb
This adds a `fraud_session_id` to the `billing_info` object so that this ID can be sent to Kount for merchants who are using that service for fraud prevention.
> Add fraud_session_id to billing_info

- CHANGELOG.md
- lib/recurly/version.rb
- Add support for fraud session ID [PR](https://github.com/recurly/recurly-client-ruby/pull/471)
> Bump to version 2.17.9

- .travis.yml
- Gemfile
- lib/recurly.rb
- lib/recurly/client.rb
- lib/recurly/client/adapter.rb
- lib/recurly/errors.rb
- lib/recurly/pager.rb
- lib/recurly/schema.rb
- lib/recurly/schema/json_deserializer.rb
- lib/recurly/schema/json_parser.rb
- lib/recurly/schema/request_caster.rb
- lib/recurly/schema/schema_factory.rb
- lib/recurly/schema/schema_validator.rb
- recurly.gemspec
- scripts/format
- scripts/test
- spec/recurly/client_spec.rb
- spec/recurly/errors_spec.rb
- spec/recurly/pager_spec.rb
- spec/recurly/request_spec.rb
- spec/recurly/resource_spec.rb
- spec/recurly/schema/json_parser_spec.rb
- spec/spec_helper.rb
- spec/test_schemas.rb
Adds `./script/format` and runs `./script/format --check` before running tests to ensure code is always formatted.
> Add format script and check in specs

- lib/recurly/billing_info.rb
- lib/recurly/transaction/errors.rb
This allows the client to use the new 3DSecure features of the API. This involves a 2 step flow with RecurlyJS, see https://github.com/recurly/recurly-js/pull/527 for technical details on that side of this process.
Script 1: Attempt to update a billing info with a credit card that requires 3DS authentication:
```ruby
account = Recurly::Account.find('x')
:first_name         => 'Verena',
:last_name          => 'Example',
:address1           => '123 Paper Street',
:city               => 'Los Angeles',
:state              => 'CA',
:zip                => '95312',
:country            => 'US',
:phone              => '555-555-5555',
:number             => '4000000000003220',
:verification_value => '123'
}
begin
account.billing_info.save!
rescue …
```
> Add 3DS tokens to transaction error and billing info

- CHANGELOG.md
- lib/recurly/api.rb
- lib/recurly/billing_info.rb
- lib/recurly/transaction/errors.rb
- lib/recurly/version.rb
<a name="v2.17.11"></a>
This brings us up to API version 2.21. There are no breaking changes.
- Add support for 3DS authenticated transactions [PR](https://github.com/recurly/recurly-client-ruby/pull/479)
> Release version 2.17.11

- lib/recurly/adjustment.rb
- lib/recurly/invoice.rb
- lib/recurly/juris_detail.rb
- lib/recurly/tax_type.rb
- spec/fixtures/adjustments/show-200-taxed.xml
- spec/fixtures/adjustments/show-200.xml
- spec/fixtures/invoices/show-200-taxed.xml
- spec/fixtures/invoices/show-200.xml
- spec/recurly/adjustment_spec.rb
- spec/recurly/invoice_spec.rb
This change only applies to customers with a Vertex integration (taxes).
Added fields
============
- `Adjustment#surcharge_in_cents`
- `Invoice#surcharge_in_cents`
- `TaxType#tax_classification`
- `JurisDetail#classification`
Removed Field
============
- `Invoice#tax_types[].type` on invoice and preview invoice endpoints.
Removes TaxType#type for invoices only, not adjustments. This is a breaking change but only for Vertex users. All other users can ignore this change.
> Changes for Vertex customers

- lib/recurly/account.rb
- lib/recurly/billing_info.rb
- lib/recurly/invoice.rb
- lib/recurly/purchase.rb
- lib/recurly/subscription.rb
- spec/recurly/invoice_spec.rb
- spec/recurly/purchase_spec.rb
As a part of PSD2, there is an exemption to exclude MOTO transactions from SCA scope.
In order to pass this indicator to the gateways, merchants need a mechanism via API
to inform Recurly of these transactions. These transactions will be initiated from
within a merchants customer service / support admin portal UI, where the customer
is not authenticated to be able to complete an SCA flow.
This is exposed to the programmer as `transaction_type` on many of the resources. Set the value to `moto` to mark the transaction as MOTO. Ex use with purchases:
```ruby
purchase = Recurly::Purchase.new({
transaction_type: 'moto',
account: {
account_code: "existingaccount",
}
subscriptions: [{ plan_code: "gold" }]
})
collection = Recurly::Purchase.invoice!(purchase)
```
> MOTO transactions

- CHANGELOG.md
- README.md
- lib/recurly/account.rb
- lib/recurly/adjustment.rb
- lib/recurly/api.rb
- lib/recurly/billing_info.rb
- lib/recurly/invoice.rb
- lib/recurly/juris_detail.rb
- lib/recurly/purchase.rb
- lib/recurly/subscription.rb
- lib/recurly/tax_type.rb
- lib/recurly/version.rb
- spec/fixtures/adjustments/show-200-taxed.xml
- spec/fixtures/adjustments/show-200.xml
- spec/fixtures/invoices/show-200-taxed.xml
- spec/fixtures/invoices/show-200.xml
- spec/recurly/adjustment_spec.rb
- spec/recurly/invoice_spec.rb
- spec/recurly/purchase_spec.rb
This bumps us to API version 2.22.
* MOTO transactions #493
* Changes for Vertex customers #491
There is one breaking change. It only applies to Vertex users so will not likely affect you.
`Invoice#tax_types[].type` on invoice and preview invoice endpoints is no longer returned.
> Release version 2.18.0 / API version 2.22

- lib/recurly.rb
Forces you to be explicit when setting strict mode. This means you can set RECURLY_STRICT_MODE=false and it will be disabled. This is for testing only and has no effect on users.
> Only set strict mode when env explicitly true

- docs/README.md
- lib/recurly/client.rb
- lib/recurly/client/operations.rb
- scripts/build
- scripts/format
- scripts/test
- spec/recurly/client_spec.rb
A client no longer needs to provide the site id, it can be inferred from
the API key. It's now optional when initializing the client.
I also added a way to optionally pass it into any operation. This will
set us up for when we have oauth and one authenticated client can
access many sites.
> Remove the site-id constraint from Client

- CHANGELOG.md
- lib/recurly/version.rb
* Adds NewShippingAddressNotification webhook [PR](https://github.com/recurly/recurly-client-ruby/pull/502)
* PSD2 billing info changes [PR](https://github.com/recurly/recurly-client-ruby/pull/505)
> Release 2.18.1

- lib/recurly/account_acquisition.rb
- lib/recurly/resource.rb
Fixes #487 
This client was trying to guess paths and xml keys for AccountAcquisition.
This resulted in 404s when trying to save account acquisitions:
```
<errors>
<error>No route matches [POST] "/v2/accounts/8c712547f23%40example.com/account_acquisition"</error>
</errors>
```
Added overrides for those 2 things. You should be able to build, save,
and update account aquisitions now.
This fixes the case as described in #487 
```ruby
account.build_account_acquisition
account.account_acquisition.channel = acquisition_params[:channel]
account.account_acquisition.subchannel = acquisition_params[:subchannel]
account.account_acquisition.campaign = acquisition_params[:campaign]
account.account_acquisition.save!
```
> Fix account acquisition href problems

- README.md
Instead of keeping track of which versions we do and do not support, our
policy is to support whatever the Ruby maintainers support. So this describes that policy and links
to a page that is always up to date with that information.
> Reference Ruby support page

- benchmark.rb
- lib/recurly/request.rb
- lib/recurly/schema.rb
- lib/recurly/schema/json_parser.rb
- lib/recurly/schema/request_caster.rb
- lib/recurly/schema/resource_caster.rb
- lib/recurly/schema/schema_factory.rb
- lib/recurly/schema/schema_validator.rb
- spec/recurly/client_spec.rb
- spec/recurly/request_spec.rb
- spec/recurly/resource_spec.rb
This restructures the schema representation to a similar style I took with the node client: https://github.com/recurly/recurly-client-node/blob/e4f03fc1e831aeb773a574dd9823255ab746ee93/lib/recurly/schemas.js
It makes the code cleaner and easier to test, and also means a lot fewer conditionals and checks at runtime so it's more performant as well.
Here's before and after on the JSON parsing / casting of a response:
```
user     system      total        real
0.210000   0.000000   0.210000 (  0.212076)
```
```
user     system      total        real
0.130000   0.000000   0.130000 (  0.133469)
```
> Refactor internal schema representation

- lib/recurly/api.rb
Require openssl
Add `OpenSSL::OPENSSL_VERSION` to `.user_agent` to address when `OpenSSL::OPENSSL_LIBRARY_VERSION` does not exist.
> Include OpenSSL::OPENSSL_LIBRARY_VERSION

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
* Fix account acquisition href problems [PR](https://github.com/recurly/recurly-client-ruby/pull/508)
* V2 bump script [PR](https://github.com/recurly/recurly-client-ruby/pull/509)
* Update travis options [PR](https://github.com/recurly/recurly-client-ruby/pull/512)
* Reference Ruby support page [PR](https://github.com/recurly/recurly-client-ruby/pull/513)
* Include OpenSSL::OPENSSL_LIBRARY_VERSION [PR](https://github.com/recurly/recurly-client-ruby/pull/514)
> Release 2.18.2

- lib/recurly/purchase.rb
- spec/recurly/purchase_spec.rb
- Added `has_one :shipping_address` relationship to `Purchase` object
- Updated test file to account for shipping address
- Updated example docs in `purchase.rb`
> Add shipping address to purchase object

- .travis.yml
Just temporary until it starts working again.
> Allow failures on 2.7 until it works again

- lib/recurly/subscription.rb
- spec/recurly/subscription_spec.rb
Adds "term_end" to the Timeframe values. This affects
Subscription#update, Subscription#preview and Subscription#cancel.
Subscription#update and Subscription#preview have been updated to no longer accept the "renewal" value for timeframe.
Instead, merchants will be able to send timeframes of "bill_date" or "term_end".
These timeframes are aligned to "current_period_ends_at" and "current_term_ends_at", respectively.
Subscription#cancel has been updated to accept the "timeframe" parameter. It accepts values of "bill_date" or "term_end".
> Subscription timeframe changes

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
Release 2.18.3
* Subscription timeframe changes [PR] (https://github.com/recurly/recurly-client-ruby/pull/492)
* Add shipping address to purchase object [PR] (https://github.com/recurly/recurly-client-ruby/pull/522)
> Release 2.18.3

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
Release 2.18.4
This bumps us to API version 2.24.
* Add Item class [PR] (https://github.com/recurly/recurly-client-ruby/pull/527)
* Hardcode reactivate function for Item class [PR] (https://github.com/recurly/recurly-client-ruby/pull/531)
> Release 2.18.4

- .bumpversion.cfg
- lib/recurly/schema.rb
- lib/recurly/schema/json_parser.rb
- lib/recurly/version.rb
Resolves #536
The `const_defined?` and `const_get` methods will search the full ancestor tree and will provide a result for the top most matching constant when the `inherit` parameter is true. This causes issues when an application has constants defined on the top level scope that share names with Recurly constants.
The issue was verified to exist using the `bin/pry` script:
```ruby
[1] pry(main)> require 'recurly'
=> true
[2] pry(main)> Recurly::Schema.get_recurly_class(:Invoice)
=> Recurly::Resources::Invoice
[3] pry(main)> class Invoice; end
=> nil
[4] pry(main)> Recurly::Schema.get_recurly_class(:Invoice)
=> Invoice
```
After the change, the same test produces the correct result:
```ruby
[1] pry(main)> require 'recurly'
=> true
[2] pry(main)> …
```
> Disable searching ancestors when looking up constants

- .bumpversion.cfg
- lib/recurly/schema/schema_validator.rb
- lib/recurly/version.rb
- spec/recurly/request_spec.rb
Resolves #538 
The client does some light type and spell checking on requests. It should skip type-checking for nil values.
This also bumps to `3.1.2`.
> Skip request property type validation for nil values

- lib/recurly/schema/resource_caster.rb
`object` was not being let through the parser but is needed in some cases. We will let it through for every type now.
Resolves #543
> Allow object attributes through

- lib/recurly/item.rb
Reconfigure `Item#reactivate` to reference reactivate link. Replaces https://github.com/recurly/recurly-client-ruby/blob/ab65ccb3514ec6cfe52c52d5e76888f19ddcc138/lib/recurly/item.rb#L31-L34.
> Reference reactivate href in xml

- .bumpversion.cfg
- lib/recurly/pager.rb
- lib/recurly/version.rb
Fixes an issue with requesting a list of resources with specific `ids`. The server expects a CSV string of ids, but the api spec specifies that the `ids` should be specified as an array. 
This fix maintains developer happiness by maintaining the ability to specify an array of ids that are transformed to a CSV string when the request is sent to the server.
> Convert Array params to CSV strings

- lib/recurly/client.rb
- lib/recurly/schema/json_parser.rb
- lib/recurly/schema/request_caster.rb
- lib/recurly/schema/resource_caster.rb
- lib/recurly/schema/schema_validator.rb
- recurly.gemspec
Resolves #548
Allows consumers of library to use newer versions of Faraday (but still restricting use of 1.0.0).
> Loosen version restriction on faraday

- lib/recurly/api.rb
- lib/recurly/subscription.rb
- spec/fixtures/subscriptions/convert-trial-200.xml
- spec/fixtures/subscriptions/show-200-trial.xml
- spec/recurly/subscription_spec.rb
To convert trial to paid subscription with 3ds token:
```ruby
subscription.convert_trial(token)
```
To convert trial for non-3ds where subscription has billing info:
```ruby
subscription.convert_trial
```
To convert trial to paid subscription when `transaction_type = moto`:
```ruby
subscription.convert_trial_moto
```
> Add convert_trial() to Subscription

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
This bumps us to API version 2.25.
* Add external_sku to Adjustment (included in API version 2.24) (https://github.com/recurly/recurly-client-ruby/pull/551)
* Add convert_trial() to Subscription (https://github.com/recurly/recurly-client-ruby/pull/553)
> Release 2.18.7

- recurly.gemspec
Updates the rake gem to 12.3.3 to resolve security issues.
https://github.com/advisories/GHSA-jppv-gw3r-w3q8
> Update rake to 12.3.3

- lib/recurly.rb
- lib/recurly/add_on.rb
- lib/recurly/api.rb
- lib/recurly/tier.rb
- spec/fixtures/plans/add_ons/index-200-tiered.xml
- spec/fixtures/plans/show-200-tiered.xml
- spec/recurly/add_on_spec.rb
To create add-on with tiered pricing:
```ruby
add_on = plan.add_ons.create!(
add_on_code:             add_on_code,
name:                    add_on_code,
tier_type:               "tiered",
tiers:                   [
Recurly::Tier.new({
unit_amount_in_cents: 5000,
ending_quantity:     2000
}),
Recurly::Tier.new({
unit_amount_in_cents: 3500
})
]
)
```
> Tiered pricing

- lib/recurly/client.rb
- lib/recurly/http.rb
- spec/recurly/client_spec.rb
Following up on 2 fixes for #568
* The request in the exposed metadata should be of type
Recurly::HTTP::Request not net/http's Request. This was not caught
because they have the same interface
* Account for null content-types
> Follow up bug fixes for #568

- lib/recurly/add_on.rb
- spec/fixtures/plans/item_backed_add_ons/index-200.xml
- spec/fixtures/plans/show-200-item-backed.xml
- spec/recurly/add_on_spec.rb
To create item-backed add-on:
```ruby
add-on = plan.add_ons.create!(
item_code:               item.item_code,
unit_amount_in_cents:    20
)
```
To get an item-backed-add-on:
```ruby
plan.add_ons.find(item.item_code)
```
To update item-backed add-on:
```ruby
add_on.update_attributes(default_quantity: 4)
```
When add-on has an associated item, only the following attributes are updatable:
```ruby
unit_amount_in_cents
default_quantity
display_quantity_on_hosted_page
optional
```
> Add item_code to AddOn

- lib/recurly/billing_info.rb
A mandate reference is a specific ID used in a payment system to show that an agreement was made between the customer and the merchant. It is often required for compliance reasons to display when a billing info is created or a payment is created.
> Add mandate_reference attribute to BillingInfo

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
This bumps us to API version 2.26.
* Add item_code to AddOn (included in API version 2.25) [PR](https://github.com/recurly/recurly-client-ruby/pull/559)
* Add SEPA IBAN attributes to billing_info [PR](https://github.com/recurly/recurly-client-ruby/pull/562)
* Tiered pricing [PR](https://github.com/recurly/recurly-client-ruby/pull/565)
* Add mandate_reference attribute to BillingInfo [PR](https://github.com/recurly/recurly-client-ruby/pull/572)
> Release 2.18.8

- recurly.gemspec
Add `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, `homepage_uri`, and `source_code_uri` to the gemspec metadata.
These [project metadata](https://guides.rubygems.org/specification-reference/#metadata) will facilitate easy access to project information. The URI will be available on the [Rubygems project page](https://rubygems.org/gems/recurly), via the rubygems API, and the `gem` and `bundle` command-line tools with the next release.
> Add project metadata to the gemspec

- lib/recurly/client.rb
- lib/recurly/http.rb
- lib/recurly/pager.rb
- spec/recurly/client_spec.rb
- spec/recurly/pager_spec.rb
Adds the `first` and `count` methods to the `Pager` class.
The `first` method will perform a request to the API with the `limit` set to 1 and will only return the first result from the server.
The `count` method will perform a `HEAD` request to the API for the appropriate endpoint. The value of the response header, `recurly-total-records`, will be returned. This is the total number of records that will be returned by the pager.
> Adding #first and #count methods to Pager

- .github/workflows/docs.yml
- README.md
Rubydoc.info consistently loses our project. It's very disruptive and we have little control over the process. This is an attempt to host the rubydocs with github pages.
> Use github pages for docs

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
* Add missing association to support Tiered Pricing [PR](https://github.com/recurly/recurly-client-ruby/pull/576)
> Release 2.18.9

- lib/recurly/client.rb
- spec/recurly/client_spec.rb
After 2020-04-09, API v3 will support an `Idempotency-Key` header so we can safely resubmit POST, PUT, and DELETE requests. Adding this header makes the requests more resilient.
Adds one retry for GET requests that return a 5xx server error. These requests are somewhat likely to succeed on a retry.
> Set an Idempotency-Key header, retry GET requests after 5xx errors

- lib/recurly/client.rb
- lib/recurly/pager.rb
- spec/recurly/client_spec.rb
- spec/recurly/pager_spec.rb
Only the `Pager` requests were including the optional query parameters when performing API requests.
This update moves the logic to handle query params from the `Pager` to the `Client` and consolidates some resulting portions of the `Pager` and `Client`
> Fixing the omission of query params

- lib/recurly/client.rb
- spec/recurly/client_spec.rb
Adding a validation method that will ensure that path parameters are not empty strings to address issues where a `get_*` operation (`/resources/{resource_id}`) does not get handled by the API as a `list_*` operations (`/resources/`). The validation will also ensure that only approved types are used.
> Ensure that path parameters are not empty strings

- GETTING_STARTED.md
Make sure these are documented in the getting started guide.
> Document `Pager#first` and `Pager#count`

- .bumpversion.cfg
- GETTING_STARTED.md
This ensures that the version number in the install instructions of the the GETTING_STARTED doc stays up to date.
> Let bump2version manage the getting started doc

- scripts/format
When the tests fail due to a code format error, the message is not very clear:
```
[I] ⋊> ~/R/v/c/ruby on clearer-error-message-with-formatting ⨯ ./scripts/test                                                                                                                 
Checking style...
Formatting ./spec/recurly/client_spec.rb produced changes
```
This change adds a nicer error message:
```
[I] ⋊> ~/R/v/c/ruby on clearer-error-message-with-formatting ⨯ ./scripts/test                                                                                                                
Checking style...
Formatting ./spec/recurly/client_spec.rb produced changes
Code is not properly formatted. Please execute ./scripts/format to autoformat the code.
```
> Better format error message

- GETTING_STARTED.md
- lib/recurly/client.rb
- spec/recurly/client_spec.rb
This adds a `logger` option when creating the Client. It also slims down some of the logging messages. By default we will set the logging level to `INFO` which only logs high level HTTP details:
```
I, [2020-05-28T18:43:13.164922 #119]  INFO -- Recurly: [Request] method="POST" path="/accounts"
I, [2020-05-28T18:43:13.362743 #119]  INFO -- Recurly: [Response] time_ms=197 status="201" method="POST" path="/accounts"
I, [2020-05-28T18:43:13.364346 #119]  INFO -- Recurly: [Request] method="DELETE" path="/accounts/code-0d18c3c49f7"
I, [2020-05-28T18:43:13.525843 #119]  INFO -- Recurly: [Response] time_ms=161 status="200" method="DELETE" path="/accounts/code-0d18c3c49f7"
```
Setting level `DEBUG` will log things like headers and request / response bodies.
> Support the programmer passing their own logger

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.5.0...HEAD)
- Latest Features [\#592](https://github.com/recurly/recurly-client-ruby/pull/592) ([bhelx](https://github.com/bhelx))
- Support the programmer passing their own logger [\#590](https://github.com/recurly/recurly-client-ruby/pull/590) ([bhelx](https://github.com/bhelx))
- Better format error message [\#593](https://github.com/recurly/recurly-client-ruby/pull/593) ([bhelx](https://github.com/bhelx))
- Let bump2version manage the getting started doc [\#591](https://github.com/recurly/recurly-client-ruby/pull/591) ([bhelx](https://github.com/bhelx))
- Document `Pager#first` and `Pager#count` [\#589](https://github.com/recurly/recurly-client-ruby/pull/589 …
> Release 3.6.0

- lib/recurly/client.rb
- spec/recurly/client_spec.rb
Fixes bug that prevents `:headers` from being included in an operation's `options`
> Allow :headers to be included in operations

- lib/recurly/api.rb
- lib/recurly/plan.rb
- lib/recurly/subscription/add_ons.rb
- lib/recurly/subscription_add_on.rb
- spec/recurly/subscription_spec.rb
This PR adds support for items on subscriptions, where merchants may now associate a subscription add-on with an item in their catalog.
`allow_any_item_on_subscriptions` has been added to the `Plan` class. It is used to determine whether items can be assigned as add-ons to individual subscriptions. If `true`, items can be assigned as add-ons to individual subscription add-ons. If `false`, only plan add-ons can be used.
`add_on_source`, added to the `SubscriptionAddOn` class, is used to determine where the associated add-on data is pulled from. If this value is set to `plan_add_on` or left blank, then add-on data will be pulled from the plan's add-ons. If the associated  `plan` has `allow_any_item_on_subscriptions` set to `true` and this field is set to `item`, then the associated add-on …
> Support items on subscriptions

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.6.0...HEAD)
- Mon Jun 29 17:01:25 UTC 2020 Upgrade API version v2019-10-10 [\#601](https://github.com/recurly/recurly-client-ruby/pull/601) ([douglasmiller](https://github.com/douglasmiller))
**Fixed bugs:**
- Allow :headers to be included in operations [\#597](https://github.com/recurly/recurly-client-ruby/pull/597) ([douglasmiller](https://github.com/douglasmiller))
- Fix doc link [\#596](https://github.com/recurly/recurly-client-ruby/pull/596) ([bhelx](https://github.com/bhelx))
> Release 3.7.0

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
This bumps us to API version 2.27. There are no breaking changes.
* BACS support https://github.com/recurly/recurly-client-ruby/pull/595
* Support items on subscriptions https://github.com/recurly/recurly-client-ruby/pull/598
> Release 2.18.10

- lib/recurly/subscription_add_on.rb
If you are creating a SubscriptionAddOn from a Plan AddOn. Example:
```ruby
a = Recurly::SubscriptionAddOn.new(plan_add_on)
```
you'll receive an exception because AddOn does not have the `add_on_source` method.
> Fix sub-add-on init bug

- lib/recurly/errors/api_errors.rb
- spec/recurly/errors_spec.rb
Non-breaking update to error classes to give them a hierarchical structure. This will facilitate differentiating between a `ClientError` and a `ServerError` for example.
New error classes have also been added to be parent classes for some existing errors (e.g. `ForbiddenError` is a new class and both `InvalidApiKeyError` and `InvalidPermissionsError` extend it)
> Adding hierarchical errors

- GETTING_STARTED.md
- lib/recurly/client.rb
- lib/recurly/client/operations.rb
- lib/recurly/pager.rb
- spec/recurly/pager_spec.rb
This is an update for the `4.x` version of the client.
This updates how optional parameters are specified in operations. In the `3.x` version of the client, optional parameters were specified an optional keyword arguments directly on each operation. This `4.x` update moves these parameters into a hash whose key, `:params` is an optional keyword argument on the operation. 
This is to facilitate additional options that may be passed into each operation (e.g. `:headers` for custom headers). 
The ability to specify custom headers was added to the `3.x` clients in https://github.com/recurly/recurly-client-ruby/pull/597, though this solution is not very future flexible.
Existing `3.x` code sample:
```ruby
options = {
limit: 200,
headers: {
'Accept-Language' => 'fr'
}
}
accounts = …
```
> Updating 4.x client to expect query string params as ['params']

- lib/recurly/add_on.rb
- lib/recurly/resource.rb
- lib/recurly/subscription_add_on.rb
- lib/recurly/tier.rb
This PR patches https://github.com/recurly/recurly-client-ruby/pull/565 and https://github.com/recurly/recurly-client-ruby/pull/576 by including an association between SubscriptionAddOn and Tier to enable updating quantity-based sub add-ons. Note that this change will trigger the following error because `unit_amount_in_cents` is sent as `Recurly::Money` instead of as an `Integer`. This error will be addressed in a separate ticket.
```
<error>
<symbol>invalid_xml</symbol>
<description>The provided XML was invalid.</description>
<details>Tag &lt;unit_amount_in_cents&gt; must contain only text</details>
</error>
```
Code example:
```ruby
subscription = Recurly::Subscription.find('insert-uuid')
sub_add_on = subscription.subscription_add_ons[0]
updated_add_on = …
```
> Establish association between Tier and SubscriptionAddOn

- lib/recurly/api.rb
- lib/recurly/billing_info.rb
Allows merchants to specify individual tax identifiers for customers (CPF + Brazil support) when creating and updating billing information.
Two fields introduced:
`tax_identifier`
`tax_identifier_type`
Example code:
```ruby
first_name: 'Chickpea',
last_name: 'Batard',
address1: '11060 US-31',
city: 'Elk Rapids',
state: 'MI',
zip: '49629',
country: 'US',
number: '4111-1111-1111-1111',
month: 12,
year: 2045,
tax_identifier: '758.356.352-65',
tax_identifier_type: 'cpf'
}
account.billing_info.save!
```
> Add tax identifier fields to billing info

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/api.rb
- lib/recurly/billing_info.rb
- lib/recurly/version.rb
This PR merges v2.29 features into v2 branch for release and bumps the client library version to 2.18.14.
---
This bumps us up to API version 2.29. There are no breaking changes.
* Add tax identifier fields to billing info https://github.com/recurly/recurly-client-ruby/pull/625
> Release 2.18.14

- lib/recurly/client.rb
This is a follow-up PR to https://github.com/recurly/recurly-client-ruby/pull/624 which removes the now defunct method `set_site_id` method.
> Removing unused method 'set_site_id'

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.11.0...HEAD)
- Mon Aug 31 19:44:58 UTC 2020 Upgrade API version v2019-10-10 [\#632](https://github.com/recurly/recurly-client-ruby/pull/632) ([douglasmiller](https://github.com/douglasmiller))
- Code of Conduct [\#631](https://github.com/recurly/recurly-client-ruby/pull/631) ([bhelx](https://github.com/bhelx))
> Release 3.12.0

- lib/recurly.rb
- lib/recurly/billing_info.rb
- lib/recurly/verify.rb
- spec/fixtures/billing_info/verify-200.xml
- spec/fixtures/billing_info/verify-422.xml
- spec/recurly/billing_info_spec.rb
If the account has billing information for anything other than a credit card, this will return 422, with an appropriate error message. If successful, this will return 200, with the transaction's data.
gateway_code (optional) is the code for the gateway to use for the verification. If unspecified, a gateway will be selected using the normal rules.
Example:
```ruby
billing_info.verify()
billing_info.verify({gateway-code: "gateway-code"})
```
> New endpoint to verify an account's billing information

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.13.0...HEAD)
- Mon Oct 19 20:38:03 UTC 2020 Upgrade API version v2019-10-10 [\#642](https://github.com/recurly/recurly-client-ruby/pull/642) ([douglasmiller](https://github.com/douglasmiller))
- Fixes uninitialized constant `Recurly::Errors::ServiceNotAvailableError` [\#641](https://github.com/recurly/recurly-client-ruby/pull/641) ([ruyrocha](https://github.com/ruyrocha))
> Release 3.14.0

- lib/recurly/coupon.rb
- spec/fixtures/coupons/show-200.xml
- spec/recurly/coupon_spec.rb
Add `item_codes` and `applies_to_all_items` to Coupon
Example
```ruby
coupon = Recurly::Coupon.create!(
coupon_code:      'special',
name:             'Special',
discount_type:    'dollars',
discount_in_cents: 2_00,
applies_to_all_items: false,
item_codes: ['one_item', 'two_item'],
)
```
> Support item-specific coupons

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
- Bump to Ruby client library version 2.18.16
- Update changelog
-------
* Support item-specific coupons https://github.com/recurly/recurly-client-ruby/pull/644
> Release 2.18.16

- lib/recurly/billing_info.rb
- spec/fixtures/billing_info/show-sepa-200.xml
- spec/recurly/billing_info_spec.rb
Response for https://developers.recurly.com/api-v2/v2.29/#operation/createAccountsBillingInfoBankAccount endpoint using `iban` should include `last_two`, similar to `last_four` when `account_number` is used. This patch exposes the `last_two` field. 
Test has also been fixed to include `last_two` and remove `iban`, which was included erroneously.
> Expose last_two on BillingInfo class for IBAN accounts and repair tests

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
- Bump to Ruby client library version 2.18.17
- Update changelog
---
Release includes:
* Expose `last_two` on BillingInfo class for IBAN accounts and repair tests https://github.com/recurly/recurly-client-ruby/pull/648
> Release 2.18.17

- lib/recurly/add_on.rb
- spec/fixtures/plans/item_backed_add_ons/index-200.xml
Because `item_state` and `external_sku` are included in the xml response for item-based add-ons, it would be good practice to expose this fields to the programmer.
> Expose item_state and external_sku in AddOn class

- lib/recurly/client/operations.rb
- lib/recurly/resources/subscription.rb
- openapi/api.yaml
- Adds the `state` parameter to the `list_account_coupon_redemptions` operation.
- Adds the `charge` parameter to the `terminate_subscription` operation so that a merchant can choose to not bill a customer for un-billed usage when terminating a subscription
> Latest Changes for 2019-10-10

- lib/recurly/invoice.rb
- spec/fixtures/invoices/refund-422.xml
- spec/recurly/invoice_spec.rb
Addresses https://github.com/recurly/recurly-client-ruby/issues/652
Provides more error details when a `Recurly::API::UnprocessableEntity` error is encountered. This patch exposes `Recurly::Transaction::Error` when a refund is not successful.
> Handle UnprocessableEntity error for Invoice#refund

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
- Bump Ruby client library version to 2.18.18
- Update changelog
-----
* Expose `item_state` and `external_sku` in AddOn class https://github.com/recurly/recurly-client-ruby/pull/650
* Handle UnprocessableEntity error for Invoice#refund https://github.com/recurly/recurly-client-ruby/pull/653
> Release 2.18.18

- .travis.yml
- lib/recurly/client.rb
- lib/recurly/pager.rb
- spec/recurly/client_spec.rb
Fixes issues experienced when running the client in ruby 3.x as reported in https://github.com/recurly/recurly-client-ruby/issues/664.
> Fixing issues with ruby 3.0

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.18.1...HEAD)
The 4.x major version of the client pairs with the `v2021-02-25` API version. This version of the client and the API contain breaking changes that should be considered before upgrading your integration.
All changes to the core API are documented in the [Developer Portal changelog](https://developers.recurly.com/api/changelog.html#v2021-02-25---current-ga-version)
- Remove `site_id` and `subdomain` from client initializer.  [#624]
- Remove `set_site_id` method from client.  [#627]
- Classify unexpected error responses from Recurly API via an HTTP status code mapping provided in `Recurly::Errors::ERROR_MAP`.  [#616]
- Remove `NetworkError` class. All error classes now extend the `APIError`. This means …
> Release 4.0.0

- .travis.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- lib/recurly/client.rb
- lib/recurly/pager.rb
- spec/recurly/client_spec.rb
Some updates added to the 3.x client were missed when creating the 4.x client.
> Sync updates not ported from 3.x client

- .github_changelog_generator
- scripts/build
- scripts/format
Removing the `--binstubs` flag from the internal development `scripts/build` script.
> Removing --binstubs from local development build script

- .bumpversion.cfg
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/4.0.0...HEAD)
- More ruby 3.0 [\#680](https://github.com/recurly/recurly-client-ruby/pull/680) ([douglasmiller](https://github.com/douglasmiller))
- Additional fix for ruby 3.x [\#679](https://github.com/recurly/recurly-client-ruby/pull/679) ([douglasmiller](https://github.com/douglasmiller))
- Generated Latest Changes for v2021-02-25 [\#678](https://github.com/recurly/recurly-client-ruby/pull/678) ([recurly-integrations](https://github.com/recurly-integrations))
- Sync updates not ported from 3.x client [\#671](https://github.com/recurly/recurly-client-ruby/pull/671) ([douglasmiller](https://github.com/douglasmiller))
> Release 4.0.1

- lib/recurly/client.rb
- spec/recurly/client_spec.rb
When a Client is initialized with a nil `api_key` value (a Dotenv loading issue in my case), requests fail with an opaque TypeError when `#set_headers` tries to base64 encode it:
```shell
[2] Pry(main)> subscriptions.first
TypeError: no implicit conversion of nil into String
from /usr/local/var/rbenv/versions/2.5.7/lib/ruby/2.5.0/base64.rb:39:in `pack'
```
This explicitly casts `@api_key` to a string, which makes a blank value raise a `Recurly::Errors::UnauthorizedError` instead.
> Fixes TypeError caused by attempts to Base64 encode nil @api_key values
