- README.md
Updating the year to 2015 in the copyright
> Update the copyright date to the current year

- lib/recurly/invoice.rb
- spec/fixtures/invoices/show-200.xml
- spec/recurly/invoice_spec.rb
@cbarton net_terms has been added too, tests updated and commits squashed.
> Add net_terms and collection_method to invoice resource

- CHANGELOG.md
I did not notice that this changelog entry was not placed in the correct spot
> Correct mistake in the changelog

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/recurly/version.rb
> Version 2.4.5

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/recurly/version.rb
Version bump to 2.4.6
Approvers: @shulmang
> Bump 2.4.6

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/recurly/version.rb
> Bump to version 2.4.7

- Gemfile.lock
- README.md
- lib/recurly/version.rb
* Add `cc_emails` attribute to `Account` [PR](https://github.com/recurly/recurly-client-ruby/pull/216)
* Add webhooks parsers [PR](https://github.com/recurly/recurly-client-ruby/pull/217)
* Fixed `setup_fee_accounting_code` spec [PR](https://github.com/recurly/recurly-client-ruby/pull/218)
> Bump to 2.4.8

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/recurly/version.rb
* Fixed array change tracking issue around redemptions [PR](https://github.com/recurly/recurly-client-ruby/pull/223)
> Bump to 2.4.9

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/recurly/version.rb
> Bump to 2.5.0

- CHANGELOG.md
- Gemfile.lock
- README.md
- lib/recurly/version.rb
* Add `currency` attribute to `BillingInfo` object so client can pass currency on create/update [PR](https://github.com/recurly/recurly-client-ruby/pull/231)
> Bump 2.5.1

- lib/recurly/resource.rb
Adds some comments to clarify what arguments to pass to the find method for different types of objects.
> [SUPPORTENG-548]adds comments clarifying arguments to pass to find method

- lib/recurly/subscription.rb
- spec/recurly/subscription_spec.rb
This PR addresses the bug in #241.
> modify update_attributes method in subscription class

- CHANGELOG.md
- lib/recurly/coupon.rb
Add support for free_trial coupons.
> Add free_trial_* attrs to coupon resource

- CHANGELOG.md
- lib/recurly/billing_info.rb
Adding roku attributes to billing_info so that merchants can subscribe using roku billing agreements.
> Add roku attributes to billing_info

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
- API Version 2.3 [PR](https://github.com/recurly/recurly-client-ruby/pull/253)
> Bump 2.7.0

- lib/recurly/account.rb
- lib/recurly/add_on.rb
- lib/recurly/adjustment.rb
- lib/recurly/coupon.rb
- lib/recurly/invoice.rb
- lib/recurly/plan.rb
- lib/recurly/redemption.rb
- lib/recurly/subscription.rb
- lib/recurly/transaction.rb
- spec/recurly/subscription_spec.rb
XML responses received `updated_at` fields in API version 2.2
> Add updated_at fields

- lib/recurly.rb
- lib/recurly/api.rb
- lib/recurly/delivery.rb
- lib/recurly/gift_card.rb
- lib/recurly/resource.rb
- lib/recurly/subscription.rb
- spec/fixtures/gift_cards/index-200.xml
- spec/fixtures/gift_cards/show-200.xml
- spec/recurly/gift_card_spec.rb
This is adding support for the gift card features and starts the `2.4` feature branch.
```ruby
account_data = Recurly::Account.new(account_code: "my_account_code")
account_data = {account_code: "my_account_code"}
account_uuid = SecureRandom.uuid
account_data = {
account_code: account_uuid,
email: 'sally@example.com',
first_name: 'Sally',
last_name: 'Smith',
billing_info: { # can also take a token
zip: '94110',
state: 'CA',
country: 'US',
number: '4111-1111-1111-1111',
month: 12,
year: 2019
}
}
delivery_data = {
method: 'email',
email_address: 'john@example.com',
first_name: 'John',
last_name: 'Smith',
gifter_name: 'Sally',
personal_message: 'Thanks John! -- sally'
}
gc = Recurly::GiftCard.new(
product_code: …
```
> Adding support for gift cards

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
- Support Shipping Addresses [PR](https://github.com/recurly/recurly-client-ruby/pull/259)
> Bump 2.7.2

- CHANGELOG.md
- README.md
- lib/recurly.rb
- lib/recurly/delivery.rb
- lib/recurly/gift_card.rb
- lib/recurly/resource.rb
- lib/recurly/subscription.rb
- lib/recurly/version.rb
- spec/fixtures/gift_cards/index-200.xml
- spec/fixtures/gift_cards/show-200.xml
- spec/recurly/gift_card_spec.rb
#257 didn't quite get things where we needed them.
> Add Gift Cards Work & Bump to 2.7.3

- CHANGELOG.md
- lib/recurly/measured_unit.rb
`updated_at` will be added to `MeasuredUnit` in the coming weeks
> add updated_at to MeasuredUnit

- lib/recurly/resource.rb
Trailing whitespace character and some extra whitespaces in this file causing some git noise. Let's remove.
> Remove trailing whitespace

- lib/recurly/coupon.rb
- lib/recurly/resource.rb
Fixes #270 
It's pretty straightforward, actually.
> Fix redeem bang

- lib/recurly/resource.rb
Just a code cleanup. No functional changes.
@lmnleaf Let me know if this still works the same.
> Cleanup code around message interpolation

- lib/recurly/address.rb
- lib/recurly/api.rb
- lib/recurly/billing_info.rb
- lib/recurly/shipping_address.rb
adds `geo_code` to `billing_info`, `account` level address, and `shipping_address`
> adds geo_code to billing_info, account address, and shipping address

- lib/recurly/webhook.rb
- lib/recurly/webhook/dunning_notification.rb
- lib/recurly/webhook/new_dunning_event_notification.rb
- spec/fixtures/webhooks/new-dunning-event-notification.xml
- spec/recurly/webhook/new_dunning_event_notification_spec.rb
Adds the new webhook event for new dunning notification:
https://dev.recurly.com/page/webhooks#dunning-event-notification-starting-11102016
> Add new dunning event notification

- lib/recurly/subscription.rb
> Add timeframe to subscription

- CHANGELOG.md
- README.md
- lib/recurly/version.rb
- Fix coupon redemption bug on bulk coupons #284 [PR](https://github.com/recurly/recurly-client-ruby/pull/286)
> Bump 2.7.5

- lib/recurly/usage.rb
- spec/fixtures/subscriptions/add_ons/usage/show-200.xml
Resolves #272
Description: Adds an id attribute to usage.
> adds id attribute to usage

- CHANGELOG.md
- lib/recurly/version.rb
- Fix cloudflare 502 error #296 
- Fix stack-level-too-deep for as_json #295
> Bump 2.7.6

- README.md
This point was brought up in #303 
I have a PR that focuses on improving these docs as we have not previously done a very good job of using them and keeping them up to date.
> Add yard docs link

- lib/recurly/account.rb
- lib/recurly/billing_info.rb
- lib/recurly/coupon.rb
- lib/recurly/invoice.rb
- lib/recurly/subscription.rb
- lib/recurly/transaction.rb
- spec/fixtures/accounts/show-200.xml
- spec/fixtures/billing_info/show-200.xml
- spec/fixtures/coupons/show-200.xml
- spec/fixtures/invoices/show-200.xml
- spec/fixtures/subscriptions/show-200.xml
- spec/fixtures/transactions/show-200.xml
- spec/recurly/account_spec.rb
This makes updates to reflect the changes in the 2.5 version of the Recurly API:
* adds readable attributes to account, billing info, coupon, invoice, subscription, and transaction
* adds a `force_collect` method to invoice
> adds updates for 2.5 API

- .travis.yml
- CHANGELOG.md
- lib/recurly.rb
- lib/recurly/account.rb
- lib/recurly/address.rb
- lib/recurly/adjustment.rb
- lib/recurly/api.rb
- lib/recurly/billing_info.rb
- lib/recurly/coupon.rb
- lib/recurly/invoice.rb
- lib/recurly/juris_detail.rb
- lib/recurly/resource.rb
- lib/recurly/resource/pager.rb
- lib/recurly/shipping_address.rb
- lib/recurly/subscription.rb
- lib/recurly/tax_type.rb
- lib/recurly/transaction.rb
- lib/recurly/version.rb
- spec/fixtures/accounts/show-200.xml
- spec/fixtures/adjustments/show-200-taxed.xml
- spec/fixtures/billing_info/show-200.xml
- spec/fixtures/coupons/show-200.xml
- spec/fixtures/invoices/show-200-taxed.xml
- spec/fixtures/invoices/show-200.xml
- spec/fixtures/subscriptions/show-200.xml
- spec/fixtures/transactions/show-200.xml
- spec/recurly/account_spec.rb
- spec/recurly/adjustment_spec.rb
- spec/recurly/invoice_spec.rb
Merging in the branch containing the api version 2.5 changes.
> API 2.5 Changes

- lib/recurly/resource/pager.rb
> Add sort and filter params to Pager rubydocs

- lib/recurly/plan.rb
- lib/recurly/subscription.rb
- spec/fixtures/plans/show-200.xml
- spec/fixtures/subscriptions/show-200.xml
These are some changes to the cardless free trial feature going into v2.6
> Cardless Free Trial v2.6 changes

- lib/recurly/webhook.rb
- lib/recurly/webhook/updated_account_notification.rb
- spec/fixtures/webhooks/updated-account-notification.xml
- spec/recurly/webhook/updated_account_notification_spec.rb
- spec/recurly/webhook_spec.rb
Added updated_account_notification handling.
> Added updated_account_notification handling

- lib/recurly/account.rb
- lib/recurly/account_balance.rb
- lib/recurly/adjustment.rb
- lib/recurly/billing_info.rb
- lib/recurly/coupon.rb
- lib/recurly/delivery.rb
- lib/recurly/gift_card.rb
- lib/recurly/invoice.rb
- lib/recurly/js.rb
- lib/recurly/measured_unit.rb
- lib/recurly/plan.rb
- lib/recurly/purchase.rb
- lib/recurly/redemption.rb
- lib/recurly/shipping_address.rb
- lib/recurly/subscription.rb
- lib/recurly/subscription_add_on.rb
- lib/recurly/transaction.rb
- recurly.gemspec
This is a PR to get our inline documentation (yardocs) up to date. This is still a WIP and changes will be pushed over the coming weeks.
> Updating the yardocs

- lib/recurly/purchase.rb
Adds custom invoice notes on Purchase for API version 2.8.
> Add custom invoice notes

- lib/recurly/invoice.rb
- lib/recurly/transaction.rb
- spec/fixtures/invoices/create-201-prefix.xml
- spec/fixtures/invoices/create-201.xml
- spec/fixtures/invoices/show-200.xml
- spec/fixtures/transactions/show-200.xml
- spec/recurly/invoice_spec.rb
Adds missing 2.8 subscriptions links
> Add subscriptions link to Invoice and Transaction

- .travis.yml
Updates the ruby versions on Travis to their latest (and adds ruby 2.5.0)
> Update Rubies on Travis

- lib/recurly/invoice.rb
- spec/fixtures/invoices/refund-201.xml
- spec/fixtures/invoices/refund_amount-201.xml
- spec/recurly/invoice_spec.rb
> Invoice refunds do not return InvoiceCollection

- lib/recurly/coupon.rb
> Coupon#redeem! should raise Invalid on failure

- lib/recurly/purchase.rb
- spec/recurly/purchase_spec.rb
> Auth and capture

- lib/recurly/plan.rb
- lib/recurly/subscription.rb
> API v2.13 Subscription terms

- lib/recurly/address.rb
- lib/recurly/invoice.rb
- spec/fixtures/invoices/show-200-updated.xml
- spec/recurly/invoice_spec.rb
Allow editing of an invoice from the client.
> Make changes necessary for updating an invoice from client

- lib/recurly/client.rb
- lib/recurly/errors.rb
The pager can encounter validation errors so we should be raising those. Also didn't like having the error class name included in the message since most logging prints the class name already.
> V3 Pager can error

- lib/recurly/webhook.rb
- lib/recurly/webhook/transaction_authorized_notification.rb
- spec/fixtures/webhooks/transaction-authorized-notification.xml
- spec/recurly/webhook_spec.rb
Add support for the webhook transaction_authorized
> Support TransactionAuthorizedNotification webhook

- lib/recurly/webhook.rb
- lib/recurly/webhook/low_balance_gift_card_notification.rb
- spec/fixtures/webhooks/low-balance-gift-card-notification.xml
- spec/recurly/webhook_spec.rb
Adds support for the new webhook
> Add support for Low Balance Gift Card Notification

- lib/recurly/account.rb
- lib/recurly/credit_payment.rb
- lib/recurly/gift_card.rb
- lib/recurly/invoice.rb
- lib/recurly/shipping_address.rb
- lib/recurly/subscription.rb
- lib/recurly/transaction.rb
- lib/recurly/usage.rb
- spec/fixtures/webhooks/new-credit-payment-notification.xml
- spec/fixtures/webhooks/new-dunning-event-notification.xml
- spec/recurly/webhook_spec.rb
Fixes #336 
This PR adds all of the missing properties to the relevant models based on the documentation at https://dev.recurly.com/page/webhooks. It also adds a few tests to the webhook spec that I was using while testing out my changes.
> Add missing webhook properties to models

- lib/recurly/webhook.rb
- lib/recurly/webhook/transaction_status_updated_notification.rb
- lib/recurly/webhook/updated_invoice_notification.rb
- spec/fixtures/webhooks/transaction-status-updated-notification.xml
- spec/fixtures/webhooks/updated-invoice-notification.xml
- spec/recurly/webhook_spec.rb
Fixes #430. Adds two new webhooks, `transaction_status_updated_notification` and `updated_invoice_notification`
> Add webhooks

- lib/recurly/api.rb
Adds OpenSSL version to the user agent.
> Add OpenSSL version to user_agent

- CHANGELOG.md
- lib/recurly/account.rb
- lib/recurly/api.rb
- lib/recurly/version.rb
- spec/fixtures/accounts/hierarchy/create-201.xml
- spec/fixtures/accounts/hierarchy/show-child-200.xml
- spec/fixtures/accounts/hierarchy/show-children-200.xml
- spec/fixtures/accounts/hierarchy/show-parent-200.xml
- spec/fixtures/accounts/hierarchy/update-200.xml
- spec/fixtures/accounts/hierarchy/update-no-parent-200.xml
- spec/recurly/account_spec.rb
This brings us up to API version 2.19. There are no breaking changes.
- Add support for Account Hierarchy [PR](https://github.com/recurly/recurly-client-ruby/pull/444)
> Release version 2.17.8 / API version 2.19

- README.md
- lib/recurly/version.rb
* Contains latest v2018-08-09 Changes including the purchases endpoint. https://github.com/recurly/recurly-client-ruby/pull/482
No breaking changes
> 3.0.0.beta.5

- lib/recurly/requests/account_acquisition_updatable.rb
- lib/recurly/requests/invoice_refund.rb
- lib/recurly/requests/line_item_create.rb
- lib/recurly/resources/account_acquisition.rb
- lib/recurly/resources/billing_info.rb
- lib/recurly/resources/coupon_discount.rb
- lib/recurly/resources/error_may_have_transaction.rb
- lib/recurly/resources/transaction.rb
- lib/recurly/resources/transaction_error.rb
* Latest v2018-08-09 Changes
* Includes fix for Hashes that should have been typed Resources
>  Latest v2018-08-09 Changes

- README.md
- lib/recurly/version.rb
* Latest Changes for v2018-08-09 (including fixing untyped Hashes in some spots) #484
> Bump 3.0.0.beta.6

- README.md
- lib/recurly.rb
- lib/recurly/client.rb
- lib/recurly/client/operations.rb
- lib/recurly/errors.rb
- lib/recurly/http.rb
- lib/recurly/pager.rb
- lib/recurly/requests.rb
- lib/recurly/requests/billing_info_create.rb
- lib/recurly/requests/invoice_refund.rb
- lib/recurly/resource.rb
- lib/recurly/resources.rb
- lib/recurly/resources/billing_info.rb
- lib/recurly/resources/coupon_discount.rb
- lib/recurly/resources/error_may_have_transaction.rb
- lib/recurly/schema/json_parser.rb
- spec/recurly/client_spec.rb
- spec/recurly/pager_spec.rb
- spec/recurly/schema/json_parser_spec.rb
This does have a few small breaking changes which I will document when I remove WIP.
> Expose HTTP request and response metadata

- docs/README.md
Document use of webhooks. For now, we are recommending people parse and manage them themselves.
> Document use of webhooks

- lib/recurly/webhook.rb
- lib/recurly/webhook/account_notification.rb
- spec/fixtures/webhooks/new-shipping-address-notification.xml
- spec/recurly/webhook/new_shipping_address_notification.rb
- spec/recurly/webhook_spec.rb
> Adds NewShippingAddressNotification webhook

- lib/recurly/gift_card.rb
- lib/recurly/invoice.rb
- lib/recurly/subscription.rb
- spec/recurly/gift_card_spec.rb
- spec/recurly/invoice_spec.rb
GiftCard#create
Invoice#force_collect
Subscription#update
All now optionally take billing infos
> PSD2 billing info changes

- .bumpversion.cfg
- README.md
- lib/recurly/version.rb
- scripts/bump
Took implementation from #507 and applied to v2.
> V2 bump script

- .travis.yml
- recurly.gemspec
> No longer need bundler 1.7

- lib/recurly.rb
- lib/recurly/adjustment.rb
- lib/recurly/api.rb
- lib/recurly/item.rb
- spec/fixtures/adjustments/show-200.xml
- spec/fixtures/items/create-201.xml
- spec/fixtures/items/show-200-inactive.xml
- spec/fixtures/items/show-200.xml
- spec/recurly/adjustment_spec.rb
- spec/recurly/item_spec.rb
- Add Item class to Ruby Client Library
To create an item:
```ruby
item = Recurly::Item.create!(
item_code: 'jungle_gym'
name: 'Jungle Gym'
)
```
To look up an item (`item_code` required):
```ruby
item = Recurly::Item.find('jungle_gym')
```
To create an adjustment including an `item_code`:
```ruby
account.adjustments.create(
unit_amount_in_cents:   50_00,
currency:               'USD',
quantity:               1,
item_code:              'jungle_gym',
end_date:               '2020-08-03T16:02:24Z'
)
```
> Add Item class

- lib/recurly/client.rb
- lib/recurly/client/operations.rb
- lib/recurly/http.rb
- lib/recurly/requests/item_create.rb
- lib/recurly/requests/item_update.rb
- lib/recurly/requests/line_item_create.rb
- lib/recurly/requests/pricing.rb
- lib/recurly/resources/binary_file.rb
- lib/recurly/resources/item.rb
- lib/recurly/resources/line_item.rb
- lib/recurly/resources/pricing.rb
- lib/recurly/schema/file_parser.rb
- openapi/api.yaml
- Adds capability to support `application/pdf` responses
- Adds `Item` support
> Generated Updates for API version v2019-10-10

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
* Adds pdf support https://github.com/recurly/recurly-client-ruby/pull/529
* Adds `Item` support https://github.com/recurly/recurly-client-ruby/pull/529
* Adds 3ds support https://github.com/recurly/recurly-client-ruby/pull/528
> Release 3.1.0

- lib/recurly/item.rb
- spec/fixtures/items/show-200.xml
To create an item:
```ruby
item = Recurly::Item.create!(
item_code: 'little_llama'
name: 'Little Llama'
)
```
To list all items:
```ruby
Recurly::Item.find_each do |item|
puts "Item: #{item.name}"
end
```
To look up an item (`item_code` required):
```ruby
item = Recurly::Item.find('little_llama')
```
To update an item (`item_code` required):
```ruby
item = Recurly::Item.find('little_llama') 
item.update_attributes(
description: "An item description",
accounting_code: "ui8900"
)
```
To delete an item (`item_code` required):
```ruby
item =  Recurly::Item.find('little_llama') 
item.destroy
```
To restore an item (`item_code` required):
```ruby
item =  Recurly::Item.find('little_llama') 
item.reactivate
```
To create an adjustment including an `item_code`:
```ruby
account.adjustments.create( …
```
> Hardcode reactivate function for Item class

- lib/recurly/webhook.rb
- lib/recurly/webhook/deactivated_item_notification.rb
- lib/recurly/webhook/item_notification.rb
- lib/recurly/webhook/new_item_notification.rb
- lib/recurly/webhook/reactivated_item_notification.rb
- lib/recurly/webhook/updated_item_notification.rb
- spec/fixtures/webhooks/deactivated-item-notification.xml
- spec/fixtures/webhooks/new-item-notification.xml
- spec/fixtures/webhooks/reactivated-item-notification.xml
- spec/fixtures/webhooks/updated-item-notification.xml
- spec/recurly/webhook_spec.rb
Includes
- `NewItemNotification`
- `UpdatedItemNotification`
- `DeactivatedItemNotification`
- `ReactivatedItemNotification`
> Add item notification webhooks

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
* Add Item notification webhooks (https://github.com/recurly/recurly-client-ruby/pull/533)
> Release 2.18.5

- .bumpversion.cfg
- lib/recurly/schema/json_parser.rb
- lib/recurly/version.rb
Resolves #540 
As we did with the other clients, for the time being, we are going to always use ErrorMayHaveTransaction.
> Issue 540 error may have transaction

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
* Allow object attributes through #542
> Release 3.2.0

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
* Reference reactivate href in xml (https://github.com/recurly/recurly-client-ruby/pull/535)
> Release 2.18.6

- .bumpversion.cfg
- lib/recurly/version.rb
* Loosen version restriction on faraday #549
> Release 3.2.2

- lib/recurly/adjustment.rb
- spec/fixtures/adjustments/show-200.xml
- spec/recurly/adjustment_spec.rb
To fetch `external_sku`:
```
adjustment = Recurly::Adjustment.find('charge_uuid')
puts "Adjustment: #{adjustment.external_sku}"
```
> Add external_sku to Adjustment

- lib/recurly/client/operations.rb
- lib/recurly/requests/add_on_create.rb
- lib/recurly/requests/add_on_update.rb
- lib/recurly/resources/add_on.rb
- lib/recurly/resources/add_on_mini.rb
- lib/recurly/resources/item_mini.rb
- lib/recurly/resources/payment_method.rb
- openapi/api.yaml
* convert trial endpoint
* item-backed add-ons
> Latest generated changes for v2019-10-10

- .bumpversion.cfg
- lib/recurly/version.rb
* Latest generated changes for v2019-10-10 #555
* convert trial endpoint
* item-backed add-ons
* IBAN billing info
* Link to new dev docs for webhooks #554
* Latest v2019-10-10 Changes #552
* More documentation
* `Account#has_*` flag attributes
* Include `RateLimitedError`
* Gateway Token Support
> Release 3.3.0

- .bumpversion.cfg
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.3.0...HEAD)
- Adding changelog and updated release scripts [\#566](https://github.com/recurly/recurly-client-ruby/pull/566) ([douglasmiller](https://github.com/douglasmiller))
- Thu Mar 19 21:04:19 UTC 2020 Upgrade API version v2019-10-10 [\#564](https://github.com/recurly/recurly-client-ruby/pull/564) ([douglasmiller](https://github.com/douglasmiller))
- Update rake to 12.3.3 [\#561](https://github.com/recurly/recurly-client-ruby/pull/561) ([douglasmiller](https://github.com/douglasmiller))
- Add request for stack trace in issue report [\#558](https://github.com/recurly/recurly-client-ruby/pull/558) ([bhelx](https://github.com/bhelx))
> Release 3.3.1

- .bumpversion.cfg
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.3.1...HEAD)
- Replace Faraday gem with Net::HTTP, add connection pooling & keep-alive, update CA roots [\#568](https://github.com/recurly/recurly-client-ruby/pull/568) ([isaachall](https://github.com/isaachall))
> Release 3.4.0

- .bumpversion.cfg
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.4.0...HEAD)
- Follow up bug fixes for \#568 [\#570](https://github.com/recurly/recurly-client-ruby/pull/570) ([bhelx](https://github.com/bhelx))
> Release 3.4.1

- lib/recurly.rb
- lib/recurly/add_on.rb
- lib/recurly/api.rb
- lib/recurly/billing_info.rb
- lib/recurly/tier.rb
- spec/fixtures/billing_info/show-sepa-200.xml
- spec/fixtures/plans/add_ons/index-200-tiered.xml
- spec/fixtures/plans/show-200-tiered.xml
- spec/recurly/add_on_spec.rb
- spec/recurly/billing_info_spec.rb
- Tiered Pricing: Enable Add Ons to support 3 new pricing models (Tiered, Volume, and Stairstep)
- Add IBAN bank info as a part of billing info
- Add Mandate ID as part of billing info
> Merge v2.26 features into v2 branch for release

- lib/recurly/add_on.rb
- lib/recurly/tier.rb
Establish `has_many :tiers` association in AddOn class
Include `changed_attributes()` to enable update functionality
> Add missing association to support Tiered Pricing

- lib/recurly/requests/add_on_create.rb
- lib/recurly/requests/add_on_update.rb
- lib/recurly/requests/subscription_add_on_create.rb
- lib/recurly/requests/subscription_add_on_tier.rb
- lib/recurly/requests/subscription_add_on_update.rb
- lib/recurly/requests/tier.rb
- lib/recurly/resources/add_on.rb
- lib/recurly/resources/subscription_add_on.rb
- lib/recurly/resources/subscription_add_on_tier.rb
- lib/recurly/resources/tier.rb
- openapi/api.yaml
* Add `optional` to AddOnUpdate
* Adding quantity based pricing support
> Tue Apr 14 20:21:21 UTC 2020 Upgrade API version v2019-10-10

- .bumpversion.cfg
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.4.1...HEAD)
- Tue Apr 14 20:21:21 UTC 2020 Upgrade API version v2019-10-10 [\#585](https://github.com/recurly/recurly-client-ruby/pull/585) ([bhelx](https://github.com/bhelx))
- Set an Idempotency-Key header, retry GET requests after 5xx errors [\#579](https://github.com/recurly/recurly-client-ruby/pull/579) ([isaachall](https://github.com/isaachall))
- Adding \#first and \#count methods to Pager [\#560](https://github.com/recurly/recurly-client-ruby/pull/560) ([douglasmiller](https://github.com/douglasmiller))
**Fixed bugs:**
- Fixing the omission of query params [\#581](https://github.com/recurly/recurly-client-ruby/pull/581) ([douglasmiller](https://github.com/douglasmiller)) …
> Release 3.5.0

- lib/recurly/billing_info.rb
- spec/fixtures/billing_info/show-bacs-200.xml
- spec/recurly/billing_info_spec.rb
Added `sort_code` and `type` fields to support BACS payment type.
> BACS support

- lib/recurly/api.rb
- lib/recurly/billing_info.rb
- lib/recurly/plan.rb
- lib/recurly/subscription/add_ons.rb
- lib/recurly/subscription_add_on.rb
- spec/fixtures/billing_info/show-bacs-200.xml
- spec/recurly/billing_info_spec.rb
- spec/recurly/subscription_spec.rb
- BACS support https://github.com/recurly/recurly-client-ruby/pull/595
- Items on subscriptions https://github.com/recurly/recurly-client-ruby/pull/598
> Merge v2.27 features into v2 branch for release

- lib/recurly/client/operations.rb
- lib/recurly/requests/subscription_add_on_create.rb
- lib/recurly/resources/subscription_add_on.rb
- lib/recurly/resources/subscription_change_preview.rb
- openapi/api.yaml
- Adds `preview_subscription_change` operation.
- Adds `add_on_source` attribute to `SubscriptionAddOnCreate` and `SubscriptionAddOn`.
> Wed Jul  1 02:06:24 UTC 2020 Upgrade API version v2019-10-10

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.7.0...HEAD)
- Wed Jul  1 02:06:24 UTC 2020 Upgrade API version v2019-10-10 [\#605](https://github.com/recurly/recurly-client-ruby/pull/605) ([douglasmiller](https://github.com/douglasmiller))
> Release 3.8.0

- lib/recurly/requests/subscription_add_on_create.rb
- lib/recurly/requests/subscription_add_on_update.rb
- openapi/api.yaml
- Adds `add_on_source` to `SubscriptionAddOnUpdate`
> Mon Jul  6 14:48:05 UTC 2020 Upgrade API version v2019-10-10

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.8.0...HEAD)
- Mon Jul  6 14:48:05 UTC 2020 Upgrade API version v2019-10-10 [\#608](https://github.com/recurly/recurly-client-ruby/pull/608) ([douglasmiller](https://github.com/douglasmiller))
> Release 3.9.0

- lib/recurly/add_on.rb
- lib/recurly/adjustment.rb
- lib/recurly/invoice.rb
- lib/recurly/item.rb
- lib/recurly/plan.rb
- lib/recurly/tax_detail.rb
- lib/recurly/transaction.rb
- spec/fixtures/adjustments/show-200.xml
- spec/fixtures/invoices/show-200-taxed.xml
- spec/fixtures/plans/add_ons/index-200.xml
- spec/recurly/add_on_spec.rb
- spec/recurly/adjustment_spec.rb
- spec/recurly/invoice_spec.rb
- spec/recurly/item_spec.rb
- spec/recurly/plan_spec.rb
Only used by customers who have "Avalara for Communications" integrations.
> Add support for Avalara for Communications

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
* Add support for Avalara for Communications https://github.com/recurly/recurly-client-ruby/pull/613
> Release 2.18.11

- lib/recurly/client/operations.rb
- lib/recurly/requests/add_on_create.rb
- lib/recurly/requests/add_on_update.rb
- lib/recurly/requests/measured_unit_create.rb
- lib/recurly/requests/measured_unit_update.rb
- lib/recurly/requests/subscription_add_on_create.rb
- lib/recurly/requests/subscription_add_on_update.rb
- lib/recurly/requests/subscription_purchase.rb
- lib/recurly/requests/usage_create.rb
- lib/recurly/resources/add_on.rb
- lib/recurly/resources/add_on_mini.rb
- lib/recurly/resources/measured_unit.rb
- lib/recurly/resources/subscription_add_on.rb
- lib/recurly/resources/subscription_change.rb
- lib/recurly/resources/subscription_change_preview.rb
- lib/recurly/resources/usage.rb
- openapi/api.yaml
* Usage and measured units support
* Added `invoice_collection` to response for `create_subscription_change`
* Support `add_on_type` on addons
> Latest Changes for 2019-10-10 (usage, measured units, etc)

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.9.0...HEAD)
- Latest Changes for 2019-10-10 \(usage, measured units, etc\) [\#621](https://github.com/recurly/recurly-client-ruby/pull/621) ([bhelx](https://github.com/bhelx))
- Adding hierarchical errors [\#610](https://github.com/recurly/recurly-client-ruby/pull/610) ([douglasmiller](https://github.com/douglasmiller))
> Release 3.10.0

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly/version.rb
* Remove surcharge as Avalara recommends https://github.com/recurly/recurly-client-ruby/pull/618
* Establish association between Tier and SubscriptionAddOn https://github.com/recurly/recurly-client-ruby/pull/620
> Release 2.18.13

- lib/recurly/requests/coupon_create.rb
- lib/recurly/requests/subscription_change_create.rb
- lib/recurly/resources/subscription_change.rb
- lib/recurly/resources/subscription_change_preview.rb
- openapi/api.yaml
- Adds Custom Fields to the Subscription Change and Subscription Change Preview endpoints.
> Mon Aug 31 19:44:58 UTC 2020 Upgrade API version v2019-10-10

- .bumpversion.cfg
- CHANGELOG.md
- README.md
- lib/recurly.rb
- lib/recurly/billing_info.rb
- lib/recurly/verify.rb
- lib/recurly/version.rb
- spec/fixtures/billing_info/verify-200.xml
- spec/fixtures/billing_info/verify-422.xml
- spec/recurly/billing_info_spec.rb
This PR merges new features into v2 branch for release and bumps the client library version to 2.18.15.
------
* New endpoint to verify an account's billing information https://github.com/recurly/recurly-client-ruby/pull/636
> Release 2.18.15

- lib/recurly/client/operations.rb
- lib/recurly/requests/add_on_create.rb
- lib/recurly/requests/line_item_create.rb
- lib/recurly/requests/subscription_add_on_create.rb
- lib/recurly/resources/coupon.rb
- lib/recurly/resources/export_dates.rb
- lib/recurly/resources/export_file.rb
- lib/recurly/resources/export_files.rb
- lib/recurly/resources/unique_coupon_code.rb
- lib/recurly/resources/usage.rb
- openapi/api.yaml
* Adds `get_export_dates` and `get_export_files` operations for the [Automated Exports](https://developers.recurly.com/api/v2019-10-10/index.html#tag/automated_exports) feature.
* Adds `ExportDates`, `ExportFiles`, and `ExportFile` resources to support the `Automated Exports` feature.
* Adds `bulk_coupon_code` and `bulk_coupon_id` attributes to the `UniqueCouponCode` and `Coupon` resources.
* Adds `unit_amount` and `usage_percentage` attributes to the `Usage` resource.
> Latest Changes for 2019-10-10 (Automated Exports, additional resource data attributes)

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.12.0...HEAD)
- Latest Changes for 2019-10-10 \(Automated Exports, additional resource data attributes\) [\#638](https://github.com/recurly/recurly-client-ruby/pull/638) ([douglasmiller](https://github.com/douglasmiller))
> Release 3.13.0

- lib/recurly/client.rb
- spec/recurly/client_spec.rb
> Fixes uninitialized constant `Recurly::Errors::ServiceNotAvailableError`

- lib/recurly/client/operations.rb
- openapi/api.yaml
* Adds `restore_coupon` operation.
> Mon Oct 19 20:38:03 UTC 2020 Upgrade API version v2019-10-10

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.14.0...HEAD)
- Latest Changes for 2019-10-10 \(Wallet, Item Coupons\) [\#645](https://github.com/recurly/recurly-client-ruby/pull/645) ([douglasmiller](https://github.com/douglasmiller))
> Release 3.15.0

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.15.0...HEAD)
- Latest Changes for 2019-10-10 \(tax\_identifier / tax\_identifier\_type\) [\#654](https://github.com/recurly/recurly-client-ruby/pull/654) ([douglasmiller](https://github.com/douglasmiller))
- Latest Changes for 2019-10-10 [\#651](https://github.com/recurly/recurly-client-ruby/pull/651) ([douglasmiller](https://github.com/douglasmiller))
> Release 3.16.0

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.16.0...HEAD)
- Latest Changes for 2019-10-10 [\#657](https://github.com/recurly/recurly-client-ruby/pull/657) ([douglasmiller](https://github.com/douglasmiller))
> Release 3.17.0

- lib/recurly/client/operations.rb
- lib/recurly/requests/coupon_redemption_create.rb
- lib/recurly/resources/coupon_redemption.rb
- openapi/api.yaml
* Adds `subscription_id` attribute to the `CouponRedemptionCreate` request.
* Adds `subscription_id` attribute to the `CouponRedemption` resource.
> Latest Changes for 2019-10-10

- .bumpversion.cfg
- GETTING_STARTED.md
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.17.0...HEAD)
- Latest Changes for 2019-10-10 [\#660](https://github.com/recurly/recurly-client-ruby/pull/660) ([douglasmiller](https://github.com/douglasmiller))
> Release 3.18.0

- .bumpversion.cfg
- lib/recurly/version.rb
[Full Changelog](https://github.com/recurly/recurly-client-ruby/compare/3.18.0...HEAD)
**Fixed bugs:**
- Fixing issues with ruby 3.0 [\#665](https://github.com/recurly/recurly-client-ruby/pull/665) ([douglasmiller](https://github.com/douglasmiller))
> Release 3.18.1

- lib/recurly/client/operations.rb
- openapi/api.yaml
Updates the openapi spec with latest changes.
> Generated Latest Changes for v2021-02-25

- lib/recurly/pager.rb
Resolves #677, which identifies another issue with ruby 3.x compatibility.
> Additional fix for ruby 3.x

- lib/recurly/pager.rb
Resolves #677, which identifies another issue with ruby 3.x compatibility.
> More ruby 3.0

- lib/recurly/requests/add_on_create.rb
- lib/recurly/requests/add_on_update.rb
- lib/recurly/requests/tier.rb
- lib/recurly/resources/tier.rb
- openapi/api.yaml
Adds `usage_percentage` to the `Tier` request and resource.
> Generated Latest Changes for v2021-02-25 (Usage Percentage on Tiers)

- spec/fixtures/subscriptions/add_ons/show-200-updated.xml
- spec/fixtures/subscriptions/add_ons/show-200.xml
- spec/recurly/add_on_spec.rb
- spec/recurly/subscription_spec.rb
Adding test coverage for updating subscription add-ons.
> Add tests for subscription add-ons
